import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string, vars?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Header
    'header.title': 'العين لتجارة الحاسبات',
    'header.home': 'الرئيسية',
    'header.categories': 'الفئات',
    'header.cart': 'السلة',
    'header.login': 'تسجيل الدخول',
    'header.profile': 'الملف الشخصي',
    'header.logout': 'تسجيل الخروج',
    'header.searchPlaceholder': 'ابحث عن المنتجات...',
    'header.search': 'بحث',
    'header.searchTitle': 'البحث',
    'header.searchDescription': 'ابحث عن منتجات الحواسيب والملحقات',
    'header.pcBuilder': 'بناء جهازك',
    'header.marketAnalysis': 'تحليل الأسعار',
    'header.trackOrder': 'تتبع طلبك',
    
    // Categories
    'category.all': 'جميع المنتجات',
    'category.laptops': 'أجهزة لابتوب',
    'category.desktops': 'أجهزة مكتبية',
    'category.monitors': 'شاشات',
    'category.accessories': 'ملحقات',
    'category.programs': 'برامج',
    
    // Home page
    'home.hero.title': 'أفضل أجهزة الحاسوب والملحقات',
    'home.hero.subtitle': 'اكتشف أحدث التقنيات بأفضل الأسعار',
    'home.hero.cta': 'تسوق الآن',
    'home.hero.imageAlt': 'صورة إعلانية للمتجر',
    'home.categories.title': 'تصفح حسب الفئة',
    'home.featured.title': 'المنتجات المميزة',
    'home.searchResultsFor': 'نتائج البحث عن: {query}',
    'home.showAll': 'عرض الكل',
    'home.noProducts': 'لا توجد منتجات متاحة',
    'home.noSearchResults': 'لا توجد منتجات تطابق البحث',
    'home.requestProduct': 'اطلب هذا المنتج',
    'home.requestProduct.title': 'طلب منتج غير متوفر',
    'home.requestProduct.desc': 'املأ النموذج أدناه وسنتواصل معك فور توفر المنتج',
    'home.requestProduct.productName': 'اسم المنتج المطلوب',
    'home.requestProduct.customerName': 'اسمك الكريم',
    'home.requestProduct.customerPhone': 'رقم الهاتف',
    'home.requestProduct.customerEmail': 'البريد الإلكتروني (اختياري)',
    'home.requestProduct.notes': 'ملاحظات إضافية',
    'home.requestProduct.submit': 'إرسال الطلب',
    'home.requestProduct.success': 'تم إرسال طلبك بنجاح! سنتواصل معك قريباً',
    'home.requestProduct.error': 'حدث خطأ أثناء إرسال الطلب',
    'home.loadError': 'حدث خطأ أثناء تحميل المنتجات. يرجى المحاولة مرة أخرى.',
    'home.repair.title': 'خدمة الصيانة',
    'home.repair.subtitle': 'هل جهازك يحتاج صيانة؟',
    'home.repair.description': 'نقدم خدمات صيانة احترافية لجميع أنواع الحواسيب والأجهزة الإلكترونية. فريقنا المتخصص جاهز لمساعدتك.',
    'home.repair.requestBtn': 'طلب صيانة',
    'home.repair.trackBtn': 'تتبع طلبك',
    'home.orderTracking.title': 'تتبع طلبك',
    'home.orderTracking.subtitle': 'هل لديك طلب قيد التوصيل؟',
    'home.orderTracking.description': 'تابع حالة طلبك بسهولة. أدخل رقم الطلب ورقم هاتفك للاطلاع على تفاصيل الشحن والتوصيل.',
    'home.orderTracking.trackBtn': 'تتبع الطلب',
    
    // Customer Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.myOrders': 'طلباتي',
    'dashboard.orderHistory': 'سجل الطلبات',
    'dashboard.noOrders': 'لا توجد طلبات بعد',
    'dashboard.noOrdersDesc': 'ابدأ التسوق الآن لعرض طلباتك هنا',
    'dashboard.startShopping': 'ابدأ التسوق',
    'dashboard.orderNumber': 'رقم الطلب',
    'dashboard.orderDate': 'تاريخ الطلب',
    'dashboard.orderStatus': 'حالة الطلب',
    'dashboard.orderTotal': 'المجموع',
    'dashboard.viewDetails': 'عرض التفاصيل',
    'dashboard.items': 'المنتجات',
    'dashboard.shippingAddress': 'عنوان التوصيل',
    'dashboard.paymentMethod': 'طريقة الدفع',
    'dashboard.status.pending': 'قيد الانتظار',
    'dashboard.status.confirmed': 'تم التأكيد',
    'dashboard.status.processing': 'قيد المعالجة',
    'dashboard.status.shipped': 'تم الشحن',
    'dashboard.status.delivered': 'تم التوصيل',
    'dashboard.status.cancelled': 'ملغي',
    'dashboard.loadError': 'حدث خطأ أثناء تحميل الطلبات',
    'dashboard.loginRequired': 'يجب تسجيل الدخول لعرض طلباتك',
    
    // Product
    'product.specifications': 'المواصفات',
    'product.addToCart': 'أضف إلى السلة',
    'product.inStock': 'متوفر في المخزون',
    'product.outOfStock': 'غير متوفر',
    'product.loading': 'جاري التحميل...',
    'product.notFound': 'المنتج غير موجود',
    
    // Cart
    'cart.title': 'سلة التسوق',
    'cart.description': 'إدارة منتجات سلة التسوق الخاصة بك',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.browsProducts': 'تصفح المنتجات',
    'cart.remove': 'إزالة',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.total': 'المجموع الكلي',
    'cart.checkout': 'إتمام الطلب',
    'cart.free': 'مجاني',
    'cart.quantity': 'الكمية',
    'cart.error': 'حدث خطأ أثناء تحميل السلة',
    'cart.loginRequired': 'يجب تسجيل الدخول أولاً',
    'cart.loginRequiredDesc': 'قم بتسجيل الدخول لإضافة المنتجات إلى سلة التسوق',
    'cart.addedToCart': 'تمت الإضافة للسلة',
    'cart.addedDescription': 'تم إضافة المنتج إلى سلة التسوق',
    'cart.addError': 'حدث خطأ أثناء إضافة المنتج للسلة',
    'cart.retry': 'إعادة المحاولة',
    'cart.removed': 'تم الحذف',
    'cart.removedDescription': 'تم حذف المنتج من السلة',
    'cart.removeError': 'حدث خطأ أثناء حذف المنتج',
    'cart.quantityUpdateError': 'حدث خطأ أثناء تحديث الكمية',
    
    // Checkout
    'checkout.title': 'إتمام الطلب',
    'checkout.customerInfo': 'معلومات التسليم',
    'checkout.fullName': 'الاسم الكامل',
    'checkout.fullNamePlaceholder': 'أدخل الاسم الكامل',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.phone': 'رقم الهاتف',
    'checkout.address': 'العنوان التفصيلي',
    'checkout.addressPlaceholder': 'الشارع، رقم البيت، أقرب نقطة دالة',
    'checkout.governorate': 'المحافظة',
    'checkout.selectGovernorate': 'اختر المحافظة',
    'checkout.neighborhood': 'المنطقة / الحي',
    'checkout.neighborhoodPlaceholder': 'مثال: الكرادة، المنصور',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.cashOnDelivery': 'الدفع عند الاستلام',
    'checkout.cashOnDeliveryDesc': 'ادفع نقداً عند استلام الطلب',
    'checkout.zainCash': 'زين كاش',
    'checkout.zainCashDesc': 'الدفع عبر محفظة زين كاش الإلكترونية',
    'checkout.qiCard': 'كي كارد',
    'checkout.qiCardDesc': 'الدفع عبر بطاقة كي كارد المصرفية',
    'checkout.onlinePayment': 'الدفع الإلكتروني',
    'checkout.comingSoon': 'قريباً',
    'checkout.confirmOrder': 'تأكيد الطلب',
    'checkout.processing': 'جاري إنشاء الطلب...',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.subtotal': 'المجموع الفرعي',
    'checkout.shipping': 'التوصيل',
    'checkout.freeShipping': 'مجاني',
    'checkout.freeShippingThreshold': 'اطلب بقيمة {amount} د.ع أو أكثر للحصول على توصيل مجاني',
    'checkout.orderSuccess': 'تم إنشاء الطلب بنجاح!',
    'checkout.orderError': 'فشل إنشاء الطلب. يرجى المحاولة مرة أخرى.',
    'checkout.loading': 'جاري تحميل السلة...',
    'checkout.addProductsFirst': 'يرجى إضافة منتجات قبل المتابعة إلى الدفع',
    'checkout.backToStore': 'العودة للمتجر',
    
    // Order Confirmation
    'orderConfirmation.title': 'تم تأكيد طلبك!',
    'orderConfirmation.thankYou': 'شكراً لتسوقك معنا',
    'orderConfirmation.orderNumber': 'رقم الطلب',
    'orderConfirmation.orderDate': 'تاريخ الطلب',
    'orderConfirmation.orderDetails': 'تفاصيل الطلب',
    'orderConfirmation.shippingInfo': 'معلومات التوصيل',
    'orderConfirmation.paymentMethod': 'طريقة الدفع',
    'orderConfirmation.orderItems': 'المنتجات المطلوبة',
    'orderConfirmation.quantity': 'الكمية',
    'orderConfirmation.price': 'السعر',
    'orderConfirmation.subtotal': 'المجموع الفرعي',
    'orderConfirmation.shipping': 'التوصيل',
    'orderConfirmation.total': 'المجموع الكلي',
    'orderConfirmation.free': 'مجاني',
    'orderConfirmation.status': 'حالة الطلب',
    'orderConfirmation.pending': 'قيد الانتظار',
    'orderConfirmation.processing': 'قيد المعالجة',
    'orderConfirmation.shipped': 'تم الشحن',
    'orderConfirmation.delivered': 'تم التسليم',
    'orderConfirmation.cancelled': 'ملغي',
    'orderConfirmation.cashOnDelivery': 'الدفع عند الاستلام',
    'orderConfirmation.zainCash': 'زين كاش',
    'orderConfirmation.qiCard': 'كي كارد',
    'orderConfirmation.continueShopping': 'متابعة التسوق',
    'orderConfirmation.loading': 'جاري تحميل تفاصيل الطلب...',
    'orderConfirmation.notFound': 'الطلب غير موجود',
    'orderConfirmation.emailSent': 'تم إرسال تأكيد الطلب إلى بريدك الإلكتروني',
    'orderConfirmation.contactSoon': 'سيتم التواصل معك قريباً لتأكيد الطلب',
    
    // Order Tracking
    'orderTracking.title': 'تتبع طلبك',
    'orderTracking.description': 'أدخل رقم الطلب ورقم الهاتف لمعرفة حالة طلبك',
    'orderTracking.orderNumber': 'رقم الطلب',
    'orderTracking.orderNumberPlaceholder': 'ORD-01001',
    'orderTracking.phone': 'رقم الهاتف',
    'orderTracking.phonePlaceholder': '07XXXXXXXXX',
    'orderTracking.phoneHint': 'الرقم المستخدم عند الطلب',
    'orderTracking.submit': 'تتبع الطلب',
    'orderTracking.searching': 'جاري البحث...',
    'orderTracking.notFound': 'لم يتم العثور على الطلب',
    'orderTracking.notFoundDesc': 'تأكد من صحة رقم الطلب ورقم الهاتف',
    'orderTracking.invalidFormat': 'صيغة غير صحيحة',
    'orderTracking.invalidOrderNumber': 'رقم الطلب يجب أن يكون بصيغة ORD-XXXXX',
    'orderTracking.invalidPhone': 'رقم الهاتف يجب أن يبدأ بـ 07 ويتكون من 11 رقم',
    'orderTracking.orderDetails': 'تفاصيل الطلب',
    'orderTracking.backToHome': 'العودة للرئيسية',
    'orderTracking.trackAnother': 'تتبع طلب آخر',
    
    // Login
    'login.title': 'تسجيل الدخول',
    'login.description': 'أدخل بريدك وكلمة المرور، ثم رمز التحقق المرسل إلى بريدك',
    'login.otpTitle': 'رمز التحقق',
    'login.otpDescription': 'أدخل الرمز المُرسل إلى بريدك ({email})',
    'login.otpLabel': 'رمز التحقق (6 أرقام)',
    'login.otpPlaceholder': '••••••',
    'login.verifyOtp': 'تأكيد وتسجيل الدخول',
    'login.backToCredentials': 'العودة',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.register': 'إنشاء حساب',
    'login.loggingIn': 'جاري تسجيل الدخول...',
    'login.success.title': 'تم تسجيل الدخول بنجاح',
    'login.success.description': 'مرحباً بك مرة أخرى',
    'login.error.title': 'خطأ في تسجيل الدخول',
    'login.error.description': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'login.backToHome': 'العودة للرئيسية',
    'forgot.title': 'استعادة كلمة المرور',
    'forgot.description': 'أدخل بريدك الإلكتروني لإرسال رمز التحقق',
    'forgot.sendCode': 'إرسال الرمز',
    'forgot.step2': 'أدخل الرمز وكلمة المرور الجديدة',
    'forgot.newPassword': 'كلمة المرور الجديدة',
    'forgot.confirmPassword': 'تأكيد كلمة المرور',
    'forgot.reset': 'تغيير كلمة المرور',
    'forgot.backToLogin': 'العودة لتسجيل الدخول',
    'forgot.mismatch': 'كلمتا المرور غير متطابقتين',
    'change.title': 'تغيير كلمة المرور',
    'forgot.descriptionSent': 'إذا كان البريد مسجلاً سيصلك رمز خلال دقائق.',
    'change.current': 'كلمة المرور الحالية',
    'change.new': 'كلمة المرور الجديدة',
    'change.confirm': 'تأكيد كلمة المرور الجديدة',
    'change.submit': 'حفظ',
    'change.success': 'تم تحديث كلمة المرور',
    'change.mismatch': 'كلمتا المرور الجديدة غير متطابقتين',
    
    // Register
    'register.title': 'إنشاء حساب جديد',
    'register.description': 'أنشئ حسابك للبدء في التسوق',
    'register.name': 'الاسم الكامل',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.phonePlaceholder': '٠٧٩٠٠٠٠٠٠٠٠',
    'register.password': 'كلمة المرور',
    'register.passwordHint': 'يجب أن تكون 6 أحرف على الأقل',
    'register.submit': 'إنشاء حساب',
    'register.hasAccount': 'لديك حساب بالفعل؟',
    'register.login': 'تسجيل الدخول',
    'register.registering': 'جاري إنشاء الحساب...',
    'register.success.title': 'تم إنشاء الحساب بنجاح',
    'register.success.description': 'مرحباً بك في العين لتجارة الحاسبات',
    'register.error.title': 'خطأ في إنشاء الحساب',
    'register.error.description': 'حدث خطأ، يرجى المحاولة مرة أخرى',
    'register.backToHome': 'العودة للرئيسية',
    
    // Admin
    'admin.login.title': 'تسجيل دخول المسؤول',
    'admin.login.password': 'كلمة المرور',
    'admin.login.passwordPlaceholder': 'أدخل كلمة المرور',
    'admin.login.submit': 'تسجيل الدخول',
    'admin.dashboard.title': 'لوحة التحكم',
    'admin.dashboard.ordersTitle': 'إدارة الطلبات',
    'admin.dashboard.ordersCount': 'عدد الطلبات',
    'admin.dashboard.noOrders': 'لا توجد طلبات حالياً',
    'admin.dashboard.orders': 'الطلبات',
    'admin.dashboard.orderNumber': 'رقم الطلب',
    'admin.dashboard.customer': 'العميل',
    'admin.dashboard.email': 'البريد الإلكتروني',
    'admin.dashboard.phone': 'رقم الهاتف',
    'admin.dashboard.city': 'المدينة',
    'admin.dashboard.itemsCount': 'عدد العناصر',
    'admin.dashboard.item': 'عنصر',
    'admin.dashboard.total': 'المجموع',
    'admin.dashboard.status': 'الحالة',
    'admin.dashboard.date': 'التاريخ',
    'admin.dashboard.update': 'تحديث',
    'admin.dashboard.updating': 'جاري التحديث...',
    'admin.dashboard.logout': 'تسجيل الخروج',
    'admin.dashboard.pending': 'قيد الانتظار',
    'admin.dashboard.processing': 'قيد المعالجة',
    'admin.dashboard.shipped': 'تم الشحن',
    'admin.dashboard.delivered': 'تم التسليم',
    'admin.dashboard.cancelled': 'ملغاة',
    'admin.dashboard.updateSuccess': 'تم التحديث بنجاح',
    'admin.dashboard.updateSuccessDesc': 'تم تحديث حالة الطلب',
    'admin.dashboard.delete': 'حذف',
    'admin.dashboard.deleting': 'جاري الحذف...',
    'admin.dashboard.deleteOrderTitle': 'حذف الطلب',
    'admin.dashboard.deleteOrderConfirm': 'هل أنت متأكد من حذف هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.dashboard.deleteSuccess': 'تم الحذف بنجاح',
    'admin.dashboard.deleteSuccessDesc': 'تم حذف الطلب',
    'admin.dashboard.deleteError': 'خطأ',
    'admin.dashboard.deleteErrorDesc': 'فشل حذف الطلب',
    'admin.dashboard.updateError': 'خطأ',
    'admin.dashboard.updateErrorDesc': 'فشل تحديث الطلب',
    'admin.dashboard.logoutSuccess': 'تسجيل الخروج',
    'admin.dashboard.logoutSuccessDesc': 'تم تسجيل خروجك بنجاح',
    
    // Admin Notifications
    'admin.notifications.title': 'الإشعارات',
    'admin.notifications.empty': 'لا توجد إشعارات جديدة',
    'admin.notifications.newOrder': 'طلب جديد',
    'admin.notifications.markAllRead': 'تحديد الكل كمقروء',
    
    // Admin Products
    'admin.products.title': 'إدارة المنتجات',
    'admin.products.addNew': 'إضافة منتج جديد',
    'admin.products.edit': 'تعديل',
    'admin.products.delete': 'حذف',
    'admin.products.confirmDelete': 'هل أنت متأكد من حذف هذا المنتج؟',
    'admin.products.nameAr': 'الاسم بالعربي',
    'admin.products.nameEn': 'الاسم بالإنجليزي',
    'admin.products.descAr': 'الوصف بالعربي',
    'admin.products.descEn': 'الوصف بالإنجليزي',
    'admin.products.price': 'السعر',
    'admin.products.oldPrice': 'السعر القديم',
    'admin.products.category': 'الفئة',
    'admin.products.image': 'رابط الصورة',
    'admin.products.badge': 'الشارة',
    'admin.products.inStock': 'متوفر',
    'admin.products.specs': 'المواصفات (سطر لكل مواصفة)',
    'admin.products.save': 'حفظ',
    'admin.products.cancel': 'إلغاء',
    'admin.products.creating': 'جاري الإنشاء...',
    'admin.products.updating': 'جاري التحديث...',
    'admin.products.deleting': 'جاري الحذف...',
    'admin.products.actions': 'الإجراءات',
    'admin.products.manageProducts': 'إدارة المنتجات',
    'admin.products.imagePlaceholder': 'product_image.png',
    
    // Admin Customers
    'admin.customers.title': 'إدارة العملاء',
    'admin.customers.subtitle': 'عرض وإدارة حسابات العملاء',
    'admin.customers.manageCustomers': 'إدارة العملاء',
    'admin.customers.noCustomers': 'لا يوجد عملاء مسجلين حالياً',
    'admin.customers.noCustomersDesc': 'سيظهر العملاء هنا بعد تسجيلهم في المتجر',
    'admin.customers.backToDashboard': 'العودة للوحة التحكم',
    'admin.customers.name': 'الاسم',
    'admin.customers.email': 'البريد الإلكتروني',
    'admin.customers.phone': 'رقم الهاتف',
    'admin.customers.registeredAt': 'تاريخ التسجيل',
    'admin.customers.ordersCount': 'عدد الطلبات',
    'admin.customers.totalSpent': 'إجمالي المشتريات',
    'admin.customers.actions': 'الإجراءات',
    'admin.customers.view': 'عرض',
    'admin.customers.edit': 'تعديل',
    'admin.customers.delete': 'حذف',
    'admin.customers.editCustomer': 'تعديل بيانات العميل',
    'admin.customers.viewCustomer': 'عرض العميل',
    'admin.customers.deleteTitle': 'حذف العميل',
    'admin.customers.confirmDelete': 'هل أنت متأكد من حذف هذا العميل؟ هذا الإجراء لا يمكن التراجع عنه.',
    'admin.customers.cancel': 'إلغاء',
    'admin.customers.save': 'حفظ',
    'admin.customers.updating': 'جاري التحديث...',
    'admin.customers.deleting': 'جاري الحذف...',
    'admin.customers.password': 'كلمة المرور الجديدة',
    'admin.customers.passwordHint': 'اترك فارغاً لعدم التغيير',
    'admin.customers.updateSuccess': 'تم تحديث بيانات العميل بنجاح',
    'admin.customers.updateError': 'فشل تحديث بيانات العميل',
    'admin.customers.deleteSuccess': 'تم حذف العميل بنجاح',
    'admin.customers.deleteError': 'فشل حذف العميل',
    'admin.customers.customersCount': 'عدد العملاء',
    
    // Admin Programs
    'admin.programs.title': 'إدارة البرامج',
    'admin.programs.subtitle': 'إضافة وتعديل البرامج والتطبيقات',
    'admin.programs.managePrograms': 'إدارة البرامج',
    'admin.programs.addNew': 'إضافة برنامج جديد',
    'admin.programs.editProgram': 'تعديل البرنامج',
    'admin.programs.noPrograms': 'لا توجد برامج',
    'admin.programs.noProgramsDesc': 'ابدأ بإضافة أول برنامج للمتجر',
    'admin.programs.addFirst': 'إضافة أول برنامج',
    'admin.programs.backToDashboard': 'العودة للوحة التحكم',
    'admin.programs.nameAr': 'اسم البرنامج بالعربية',
    'admin.programs.nameEn': 'اسم البرنامج بالإنجليزية',
    'admin.programs.nameArPlaceholder': 'مثال: مايكروسوفت أوفيس',
    'admin.programs.nameEnPlaceholder': 'مثال: Microsoft Office',
    'admin.programs.descAr': 'الوصف بالعربية',
    'admin.programs.descEn': 'الوصف بالإنجليزية',
    'admin.programs.descArPlaceholder': 'وصف مفصل للبرنامج...',
    'admin.programs.descEnPlaceholder': 'Detailed program description...',
    'admin.programs.licenseType': 'نوع الترخيص',
    'admin.programs.licenseTypePlaceholder': 'مثال: سنوي، دائم، شهري',
    'admin.programs.version': 'الإصدار',
    'admin.programs.versionPlaceholder': 'مثال: 2024، v1.0',
    'admin.programs.price': 'السعر',
    'admin.programs.oldPrice': 'السعر القديم',
    'admin.programs.stockQuantity': 'الكمية',
    'admin.programs.imageUrl': 'رابط الصورة',
    'admin.programs.imageUrlPlaceholder': 'https://example.com/image.png',
    'admin.programs.badge': 'الشارة',
    'admin.programs.badgePlaceholder': 'مثال: جديد، خصم',
    'admin.programs.features': 'المميزات',
    'admin.programs.featuresPlaceholder': 'أدخل كل ميزة في سطر جديد...',
    'admin.programs.inStock': 'التوفر',
    'admin.programs.available': 'متوفر',
    'admin.programs.unavailable': 'غير متوفر',
    'admin.programs.image': 'الصورة',
    'admin.programs.actions': 'الإجراءات',
    'admin.programs.edit': 'تعديل',
    'admin.programs.delete': 'حذف',
    'admin.programs.deleteTitle': 'حذف البرنامج',
    'admin.programs.confirmDelete': 'هل أنت متأكد من حذف هذا البرنامج؟ هذا الإجراء لا يمكن التراجع عنه.',
    'admin.programs.cancel': 'إلغاء',
    'admin.programs.save': 'حفظ',
    'admin.programs.creating': 'جاري الإنشاء...',
    'admin.programs.updating': 'جاري التحديث...',
    'admin.programs.deleting': 'جاري الحذف...',
    
    // Admin Settings
    'admin.settings.title': 'إعدادات المتجر',
    'admin.settings.storeInfo': 'معلومات المتجر',
    'admin.settings.storeInfoDesc': 'قم بتحديث اسم المتجر ووصفه',
    'admin.settings.contactInfo': 'معلومات الاتصال',
    'admin.settings.contactInfoDesc': 'قم بتحديث البريد الإلكتروني والهاتف والموقع',
    'admin.settings.socialMedia': 'وسائل التواصل الاجتماعي',
    'admin.settings.socialMediaDesc': 'قم بإضافة روابط حساباتك على وسائل التواصل',
    'admin.settings.storeNameAr': 'اسم المتجر بالعربية',
    'admin.settings.storeNameEn': 'اسم المتجر بالإنجليزية',
    'admin.settings.descriptionAr': 'الوصف بالعربية',
    'admin.settings.descriptionEn': 'الوصف بالإنجليزية',
    'admin.settings.email': 'البريد الإلكتروني',
    'admin.settings.phone': 'رقم الهاتف',
    'admin.settings.phoneAr': 'رقم الهاتف بالعربية',
    'admin.settings.addressAr': 'العنوان بالعربية',
    'admin.settings.addressEn': 'العنوان بالإنجليزية',
    'admin.settings.hoursAr': 'ساعات العمل بالعربية',
    'admin.settings.hoursEn': 'ساعات العمل بالإنجليزية',
    'admin.settings.facebookUrl': 'رابط فيسبوك',
    'admin.settings.twitterUrl': 'رابط تويتر',
    'admin.settings.instagramUrl': 'رابط انستجرام',
    'admin.settings.whatsappNumber': 'رقم واتساب',
    'admin.settings.whatsappNumberHint': 'رقم الهاتف (مثال: 07701234567)',
    'admin.settings.save': 'حفظ الإعدادات',
    'admin.settings.successTitle': 'تم الحفظ',
    'admin.settings.successMessage': 'تم حفظ إعدادات المتجر بنجاح',
    'admin.settings.errorMessage': 'فشل حفظ الإعدادات',
    'admin.settings.manageSettings': 'إعدادات المتجر',
    'admin.settings.validation.storeNameArRequired': 'اسم المتجر بالعربية مطلوب',
    'admin.settings.validation.storeNameEnRequired': 'اسم المتجر بالإنجليزية مطلوب',
    'admin.settings.validation.descriptionArRequired': 'الوصف بالعربية مطلوب',
    'admin.settings.validation.descriptionEnRequired': 'الوصف بالإنجليزية مطلوب',
    'admin.settings.validation.emailInvalid': 'البريد الإلكتروني غير صحيح',
    'admin.settings.validation.phoneRequired': 'رقم الهاتف مطلوب',
    'admin.settings.validation.phoneArRequired': 'رقم الهاتف بالعربية مطلوب',
    'admin.settings.validation.addressArRequired': 'العنوان بالعربية مطلوب',
    'admin.settings.validation.addressEnRequired': 'العنوان بالإنجليزية مطلوب',
    'admin.settings.validation.hoursArRequired': 'ساعات العمل بالعربية مطلوبة',
    'admin.settings.validation.hoursEnRequired': 'ساعات العمل بالإنجليزية مطلوبة',
    
    // Admin Settings Tabs
    'admin.settings.tabs.store': 'المتجر',
    'admin.settings.tabs.theme': 'المظهر',
    'admin.settings.tabs.seo': 'SEO',
    'admin.settings.tabs.homepage': 'الصفحة الرئيسية',
    'admin.settings.tabs.footer': 'التذييل',
    'admin.settings.tabs.shipping': 'الشحن والدفع',
    
    // Theme Settings
    'admin.settings.theme.branding': 'العلامة التجارية',
    'admin.settings.theme.brandingDesc': 'قم بتحميل شعار المتجر والأيقونة',
    'admin.settings.theme.logoUrl': 'رابط الشعار',
    'admin.settings.theme.logoUrlHint': 'رابط صورة شعار المتجر',
    'admin.settings.theme.faviconUrl': 'رابط الأيقونة',
    'admin.settings.theme.faviconUrlHint': 'رابط أيقونة المتجر (favicon)',
    'admin.settings.theme.colors': 'الألوان',
    'admin.settings.theme.colorsDesc': 'اختر ألوان المتجر الأساسية',
    'admin.settings.theme.primaryColor': 'اللون الأساسي',
    'admin.settings.theme.accentColor': 'اللون الثانوي',
    'admin.settings.theme.currency': 'العملة',
    'admin.settings.theme.currencyDesc': 'إعدادات عرض العملة',
    'admin.settings.theme.currencySymbolAr': 'رمز العملة بالعربية',
    'admin.settings.theme.currencySymbolEn': 'رمز العملة بالإنجليزية',
    
    // SEO Settings
    'admin.settings.seo.metaTitle': 'عنوان الصفحة',
    'admin.settings.seo.metaTitleDesc': 'العنوان الذي يظهر في نتائج البحث',
    'admin.settings.seo.metaTitleAr': 'عنوان الصفحة بالعربية',
    'admin.settings.seo.metaTitleEn': 'عنوان الصفحة بالإنجليزية',
    'admin.settings.seo.metaDescription': 'وصف الصفحة',
    'admin.settings.seo.metaDescriptionDesc': 'الوصف الذي يظهر في نتائج البحث',
    'admin.settings.seo.metaDescriptionAr': 'وصف الصفحة بالعربية',
    'admin.settings.seo.metaDescriptionEn': 'وصف الصفحة بالإنجليزية',
    'admin.settings.seo.keywords': 'الكلمات المفتاحية',
    'admin.settings.seo.keywordsDesc': 'الكلمات المفتاحية لمحركات البحث',
    'admin.settings.seo.keywordsAr': 'الكلمات المفتاحية بالعربية',
    'admin.settings.seo.keywordsEn': 'الكلمات المفتاحية بالإنجليزية',
    'admin.settings.seo.keywordsPlaceholder': 'كلمة1، كلمة2، كلمة3',
    
    // Homepage Settings
    'admin.settings.homepage.announcement': 'شريط الإعلانات',
    'admin.settings.homepage.announcementDesc': 'إعدادات شريط العروض والإعلانات في أعلى الصفحة',
    'admin.settings.homepage.enableAnnouncement': 'تفعيل شريط الإعلانات',
    'admin.settings.homepage.announcementTextAr': 'نص الإعلان بالعربية',
    'admin.settings.homepage.announcementTextEn': 'نص الإعلان بالإنجليزية',
    'admin.settings.homepage.announcementPlaceholder': 'مثال: خصم 20% على جميع المنتجات!',
    'admin.settings.homepage.announcementBgColor': 'لون خلفية الشريط',
    'admin.settings.homepage.dismissCount': 'عدد مرات الإغلاق',
    'admin.settings.homepage.resetCount': 'إعادة تعيين',
    'admin.settings.homepage.dismissCountReset': 'تم إعادة التعيين',
    'admin.settings.homepage.dismissCountResetDesc': 'تم إعادة تعيين عداد الإغلاق إلى صفر',
    'admin.settings.homepage.scrollDirection': 'اتجاه التمرير',
    'admin.settings.homepage.scrollRtl': 'من اليمين إلى اليسار',
    'admin.settings.homepage.scrollLtr': 'من اليسار إلى اليمين',
    'admin.settings.homepage.hero': 'البانر الرئيسي',
    'admin.settings.homepage.heroDesc': 'إعدادات البانر في الصفحة الرئيسية',
    'admin.settings.homepage.showHeroBanner': 'إظهار البانر الرئيسي',
    'admin.settings.homepage.heroTitleAr': 'عنوان البانر بالعربية',
    'admin.settings.homepage.heroTitleEn': 'عنوان البانر بالإنجليزية',
    'admin.settings.homepage.heroSubtitleAr': 'العنوان الفرعي بالعربية',
    'admin.settings.homepage.heroSubtitleEn': 'العنوان الفرعي بالإنجليزية',
    'admin.settings.homepage.heroImageUrl': 'رابط صورة البانر',
    'admin.settings.homepage.heroImageHint': 'يفضل صورة بحجم 1920x600 بكسل',
    'admin.settings.homepage.sections': 'أقسام الصفحة الرئيسية',
    'admin.settings.homepage.sectionsDesc': 'تحكم في الأقسام المعروضة',
    'admin.settings.homepage.showCategories': 'إظهار قسم الفئات',
    'admin.settings.homepage.showFeaturedProducts': 'إظهار المنتجات المميزة',
    'admin.settings.homepage.featuredProductsCount': 'عدد المنتجات المميزة',
    
    // Footer Settings
    'admin.settings.footer.about': 'نص عن المتجر',
    'admin.settings.footer.aboutDesc': 'النص الذي يظهر في تذييل الصفحة',
    'admin.settings.footer.aboutTextAr': 'نص عن المتجر بالعربية',
    'admin.settings.footer.aboutTextEn': 'نص عن المتجر بالإنجليزية',
    'admin.settings.footer.copyright': 'حقوق النشر',
    'admin.settings.footer.copyrightDesc': 'نص حقوق النشر في التذييل',
    'admin.settings.footer.copyrightTextAr': 'نص حقوق النشر بالعربية',
    'admin.settings.footer.copyrightTextEn': 'نص حقوق النشر بالإنجليزية',
    'admin.settings.footer.linksTitle': 'روابط التذييل',
    'admin.settings.footer.linksDesc': 'إدارة مجموعات الروابط في تذييل الصفحة',
    'admin.settings.footer.noGroups': 'لا توجد مجموعات روابط. أضف مجموعة جديدة للبدء.',
    'admin.settings.footer.untitledGroup': 'مجموعة بدون عنوان',
    'admin.settings.footer.links': 'روابط',
    'admin.settings.footer.groupTitleAr': 'عنوان المجموعة بالعربية',
    'admin.settings.footer.groupTitleEn': 'عنوان المجموعة بالإنجليزية',
    'admin.settings.footer.groupTitlePlaceholder': 'أدخل عنوان المجموعة',
    'admin.settings.footer.linksInGroup': 'الروابط في هذه المجموعة',
    'admin.settings.footer.noLinks': 'لا توجد روابط في هذه المجموعة',
    'admin.settings.footer.labelAr': 'النص بالعربية',
    'admin.settings.footer.labelEn': 'النص بالإنجليزية',
    'admin.settings.footer.labelPlaceholder': 'نص الرابط',
    'admin.settings.footer.url': 'الرابط',
    'admin.settings.footer.external': 'رابط خارجي',
    'admin.settings.footer.addLink': 'إضافة رابط',
    'admin.settings.footer.addGroup': 'إضافة مجموعة روابط',
    'admin.settings.footer.removeGroup': 'حذف المجموعة',
    
    // Shipping Settings
    'admin.settings.shipping.title': 'إعدادات الشحن',
    'admin.settings.shipping.description': 'تحكم في تكاليف الشحن والتوصيل',
    'admin.settings.shipping.cost': 'تكلفة الشحن',
    'admin.settings.shipping.costHint': 'تكلفة الشحن بالدينار العراقي',
    'admin.settings.shipping.freeThreshold': 'حد الشحن المجاني',
    'admin.settings.shipping.freeThresholdHint': 'الحد الأدنى للطلب للحصول على شحن مجاني',
    'admin.settings.shipping.enableFreeShipping': 'تفعيل الشحن المجاني',
    
    // Payment Settings
    'admin.settings.payment.title': 'طرق الدفع',
    'admin.settings.payment.description': 'تحكم في طرق الدفع المتاحة',
    'admin.settings.payment.cashOnDelivery': 'الدفع عند الاستلام',
    'admin.settings.payment.electronicPayment': 'الدفع الإلكتروني',
    
    // Categories
    'categories.laptops': 'أجهزة لابتوب',
    'categories.desktops': 'أجهزة مكتبية',
    'categories.monitors': 'شاشات',
    'categories.accessories': 'إكسسوارات',
    
    // Footer
    'footer.about': 'عن',
    'footer.defaultStoreName': 'العين لتجارة الحاسبات',
    'footer.defaultDescription': 'متجرك الموثوق لأحدث الحواسيب والملحقات بأفضل الأسعار وأعلى جودة',
    'footer.email': 'البريد الإلكتروني:',
    'footer.phone': 'الهاتف:',
    'footer.hours': 'ساعات العمل:',
    'footer.defaultEmail': 'info@alain-computers.com',
    'footer.defaultPhone': '٩٢٠٠٠١٢٣٤',
    'footer.defaultHours': 'السبت - الخميس ٩ص - ٩م',
    'footer.quickLinks': 'روابط سريعة',
    'footer.aboutUs': 'من نحن',
    'footer.contact': 'اتصل بنا',
    'footer.branches': 'فروعنا',
    'footer.careers': 'الوظائف',
    'footer.customerService': 'خدمة العملاء',
    'footer.shipping': 'سياسة الشحن',
    'footer.returns': 'الاستبدال والاسترجاع',
    'footer.warranty': 'الضمان',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.trackOrder': 'تتبع طلبك',
    'footer.newsletter': 'اشترك في النشرة الإخبارية',
    'footer.newsletterDesc': 'احصل على آخر العروض والأخبار',
    'footer.newsletterPlaceholder': 'بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
    'footer.followUs': 'تابعنا',
    'footer.whatsapp': 'تواصل معنا عبر واتساب',
    'footer.location': 'موقعنا',
    'footer.copyright': '© ٢٠٢٥ العين لتجارة الحاسبات. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'الشروط والأحكام',
    
    // Repair Tracking
    'repair.request.title': 'طلب صيانة',
    'repair.request.description': 'أرسل جهازك للصيانة',
    'repair.request.customerInfo': 'معلومات العميل',
    'repair.request.deviceInfo': 'معلومات الجهاز',
    'repair.request.customerName': 'الاسم الكامل',
    'repair.request.customerPhone': 'رقم الهاتف',
    'repair.request.customerEmail': 'البريد الإلكتروني (اختياري)',
    'repair.request.deviceType': 'نوع الجهاز',
    'repair.request.deviceBrand': 'العلامة التجارية',
    'repair.request.deviceModel': 'الموديل',
    'repair.request.issueDescription': 'وصف المشكلة',
    'repair.request.issueDescriptionPlaceholder': 'صف المشكلة بالتفصيل...',
    'repair.request.issueDescriptionNote': 'يرجى وصف المشكلة بالتفصيل للحصول على تقدير أفضل',
    'repair.request.submit': 'إرسال طلب الصيانة',
    'repair.request.submitting': 'جاري الإرسال...',
    'repair.request.successTitle': 'تم إرسال الطلب',
    'repair.request.successMessage': 'رقم التذكرة: {ticketNumber}',
    'repair.request.successNote': 'احفظ رقم التذكرة لمتابعة حالة الصيانة',
    'repair.request.copyTicket': 'نسخ رقم التذكرة',
    'repair.request.copied': 'تم النسخ',
    'repair.request.errorTitle': 'فشل إرسال الطلب',
    'repair.request.errorMessage': 'حدث خطأ، يرجى المحاولة مرة أخرى',
    
    'repair.lookup.title': 'تتبع الصيانة',
    'repair.lookup.description': 'تحقق من حالة طلب الصيانة',
    'repair.lookup.ticketNumber': 'رقم التذكرة',
    'repair.lookup.ticketNumberPlaceholder': 'AEEN-٠٠٠٠١',
    'repair.lookup.phonePlaceholder': '٠٧٩٠٠٠٠٠٠٠٠',
    'repair.lookup.searchPlaceholder': 'رقم التذكرة أو رقم الهاتف أو رقم الإيصال',
    'repair.lookup.searchHint': 'يمكنك البحث برقم التذكرة (مثل AEEN-00001) أو رقم الهاتف أو رقم الإيصال',
    'repair.lookup.search': 'بحث',
    'repair.lookup.searching': 'جاري البحث...',
    'repair.lookup.notFound': 'لم يتم العثور على نتائج. تأكد من رقم التذكرة أو رقم الهاتف أو رقم الإيصال',
    'repair.lookup.errorMessage': 'حدث خطأ أثناء البحث',
    
    'repair.ticket.details': 'تفاصيل التذكرة',
    'repair.ticket.ticketNumber': 'رقم التذكرة',
    'repair.ticket.status': 'الحالة',
    'repair.ticket.priority': 'الأولوية',
    'repair.ticket.createdAt': 'تاريخ الإنشاء',
    'repair.ticket.updatedAt': 'آخر تحديث',
    'repair.ticket.estimatedCompletion': 'التاريخ المتوقع للإنجاز',
    'repair.ticket.costEstimate': 'التكلفة المقدرة',
    'repair.ticket.finalCost': 'التكلفة النهائية',
    'repair.ticket.technicianNotes': 'ملاحظات الفني',
    'repair.ticket.customerName': 'اسم العميل',
    'repair.ticket.customerPhone': 'هاتف العميل',
    'repair.ticket.customerEmail': 'بريد العميل',
    'repair.ticket.deviceType': 'نوع الجهاز',
    'repair.ticket.deviceBrand': 'العلامة التجارية',
    'repair.ticket.deviceModel': 'الموديل',
    'repair.ticket.issueDescription': 'وصف المشكلة',
    
    'repair.status.pending': 'قيد الانتظار',
    'repair.status.in-progress': 'قيد الصيانة',
    'repair.status.waiting-parts': 'بانتظار القطع',
    'repair.status.completed': 'مكتمل',
    'repair.status.delivered': 'تم التسليم',
    'repair.status.rejected': 'تم رفض الصيانة',
    'repair.status.unrepairable': 'لا يصلح',
    
    'repair.priority.low': 'منخفضة',
    'repair.priority.normal': 'عادية',
    'repair.priority.high': 'عالية',
    'repair.priority.urgent': 'عاجلة',
    'repair.priority.vip': 'VIP - عميل مميز',

    'repair.payment.unpaid': 'غير مدفوع',
    'repair.payment.paid': 'مدفوع',
    'repair.payment.deferred': 'آجل',
    'repair.ticket.paymentStatus': 'حالة الدفع',

    'repair.deviceType.laptop': 'لابتوب',
    'repair.deviceType.desktop': 'جهاز مكتبي',
    'repair.deviceType.monitor': 'شاشة',
    'repair.deviceType.printer': 'طابعة',
    'repair.deviceType.other': 'أخرى',
    
    'repair.technician.login.title': 'دخول الفني',
    'repair.technician.login.description': 'أدخل كلمة المرور للوصول إلى لوحة الفني',
    'repair.technician.login.password': 'كلمة المرور',
    'repair.technician.login.passwordPlaceholder': 'أدخل كلمة المرور',
    'repair.technician.login.submit': 'تسجيل الدخول',
    'repair.technician.login.successTitle': 'تم تسجيل الدخول',
    'repair.technician.login.successDescription': 'مرحباً بك مرة أخرى',
    'repair.technician.login.errorTitle': 'خطأ',
    'repair.technician.login.errorDescription': 'كلمة المرور غير صحيحة',
    
    // Technician Login (with username/password)
    'technician.login.title': 'نظام الصيانة',
    'technician.login.description': 'سجّل دخولك للوصول إلى نظام إدارة الصيانة',
    'technician.login.username': 'اسم المستخدم',
    'technician.login.usernamePlaceholder': 'أدخل اسم المستخدم',
    'technician.login.password': 'كلمة المرور',
    'technician.login.passwordPlaceholder': 'أدخل كلمة المرور',
    'technician.login.submit': 'تسجيل الدخول',
    'technician.login.loggingIn': 'جاري تسجيل الدخول...',
    'technician.login.backToHome': 'العودة للرئيسية',
    'technician.login.success.title': 'تم تسجيل الدخول بنجاح',
    'technician.login.success.description': 'مرحباً بك في نظام الصيانة',
    'technician.login.error.title': 'خطأ في تسجيل الدخول',
    'technician.login.error.description': 'اسم المستخدم أو كلمة المرور غير صحيحة',
    
    // Technician Management
    'technician.management.title': 'إدارة الفنيين',
    'technician.management.addNew': 'إضافة فني',
    'technician.management.edit': 'تعديل',
    'technician.management.delete': 'حذف',
    'technician.management.username': 'اسم المستخدم',
    'technician.management.displayName': 'الاسم الظاهر',
    'technician.management.password': 'كلمة المرور',
    'technician.management.newPassword': 'كلمة مرور جديدة',
    'technician.management.isAdmin': 'صلاحيات المسؤول',
    'technician.management.isActive': 'الحالة',
    'technician.management.active': 'نشط',
    'technician.management.inactive': 'معطل',
    'technician.management.permissions': 'الصلاحيات',
    'technician.management.permission.view_tickets': 'عرض التذاكر',
    'technician.management.permission.update_status': 'تحديث الحالة',
    'technician.management.permission.manage_tickets': 'إدارة التذاكر',
    'technician.management.permission.manage_technicians': 'إدارة الفنيين',
    'technician.management.permission.view_revenue': 'عرض الإيرادات',
    'technician.management.permission.view_daily_report': 'تقرير الصيانة',
    'technician.management.confirmDelete': 'هل أنت متأكد من حذف هذا الفني؟',
    'technician.management.deleted': 'تم حذف الفني بنجاح',
    'technician.management.created': 'تم إنشاء الفني بنجاح',
    'technician.management.updated': 'تم تحديث الفني بنجاح',
    'technician.management.noTechnicians': 'لا يوجد فنيين',
    'technician.management.leaveBlankPassword': 'اتركها فارغة للإبقاء على كلمة المرور الحالية',
    
    // Technician Dashboard
    'technician.dashboard.logout': 'تسجيل الخروج',
    'technician.dashboard.welcome': 'مرحباً، {name}',
    'repair.technician.dashboard.title': 'لوحة الفني',
    'repair.technician.dashboard.allTickets': 'جميع التذاكر',
    'repair.technician.dashboard.newTicket': 'تذكرة جديدة',
    'repair.technician.dashboard.filterStatus': 'تصفية حسب الحالة',
    'repair.technician.dashboard.filterPriority': 'تصفية حسب الأولوية',
    'repair.technician.dashboard.searchPhone': 'البحث برقم الهاتف...',
    'repair.technician.dashboard.searchNameOrPhone': 'البحث بالاسم أو رقم الهاتف...',
    'repair.technician.dashboard.searchAll': 'البحث بالاسم أو الهاتف أو رقم التذكرة...',
    'repair.technician.dashboard.noTickets': 'لا توجد تذاكر',
    'repair.whatsapp.dashboardButton': 'واتساب — كل المكتملة',
    'repair.whatsapp.confirmTitle': 'تأكيد إرسال واتساب',
    'repair.whatsapp.confirmDescription': 'إرسال رسالة «جاهز للاستلام» إلى عملاء {count} تذكرة مكتملة؟',
    'repair.whatsapp.confirmSend': 'إرسال',
    'repair.whatsapp.confirmCancel': 'إلغاء',
    'repair.whatsapp.bulkResult': 'أُرسل {sent} من {total}',
    
    'repair.edit.title': 'تحديث التذكرة',
    'repair.edit.updateStatus': 'تحديث الحالة',
    'repair.edit.updatePriority': 'تحديث الأولوية',
    'repair.edit.addNotes': 'إضافة ملاحظات',
    'repair.edit.setEstimatedCompletion': 'تحديد تاريخ الإنجاز المتوقع',
    'repair.edit.setCostEstimate': 'تحديد التكلفة المقدرة',
    'repair.edit.setFinalCost': 'تحديد التكلفة النهائية',
    'repair.edit.save': 'حفظ التغييرات',
    'repair.edit.saving': 'جاري الحفظ...',
    'repair.edit.successTitle': 'تم التحديث',
    'repair.edit.successMessage': 'تم تحديث التذكرة بنجاح',
    'repair.edit.errorMessage': 'فشل تحديث التذكرة',
    
    'repair.delete.button': 'حذف التذكرة',
    'repair.delete.title': 'حذف التذكرة',
    'repair.delete.description': 'هل أنت متأكد من حذف هذه التذكرة؟ لا يمكن التراجع عن هذا الإجراء.',
    'repair.delete.confirm': 'نعم، حذف',
    'repair.delete.cancel': 'إلغاء',
    'repair.delete.deleting': 'جاري الحذف...',
    'repair.delete.successTitle': 'تم الحذف',
    'repair.delete.successMessage': 'تم حذف التذكرة بنجاح',
    'repair.delete.errorMessage': 'فشل حذف التذكرة',
    
    // PC Builder
    'pcBuilder.title': 'بناء جهاز الكمبيوتر',
    'pcBuilder.subtitle': 'اختر المكونات وابنِ جهازك المثالي',
    'pcBuilder.backToStore': 'العودة للمتجر',
    'pcBuilder.yourBuild': 'جهازك',
    'pcBuilder.selectedParts': '{{count}} مكونات محددة',
    'pcBuilder.notSelected': 'لم يتم الاختيار',
    'pcBuilder.selected': 'محدد',
    'pcBuilder.total': 'المجموع',
    'pcBuilder.addToCart': 'إضافة للسلة',
    'pcBuilder.clearBuild': 'مسح الكل',
    'pcBuilder.estimatedPower': 'الطاقة المقدرة',
    'pcBuilder.recommendedPsu': 'مزود الطاقة الموصى به',
    'pcBuilder.psuInsufficient': 'مزود الطاقة غير كافٍ',
    'pcBuilder.noComponents': 'لا توجد مكونات متوفرة',
    'pcBuilder.previousStep': 'السابق',
    'pcBuilder.nextStep': 'التالي',
    'pcBuilder.addedToCart': 'تمت الإضافة للسلة',
    'pcBuilder.addedToCartDesc': 'تم إضافة جميع المكونات إلى سلة التسوق',
    'pcBuilder.addToCartError': 'فشل إضافة المكونات للسلة',
    'pcBuilder.component.cpu': 'المعالج',
    'pcBuilder.component.motherboard': 'اللوحة الأم',
    'pcBuilder.component.ram': 'الذاكرة',
    'pcBuilder.component.gpu': 'كرت الشاشة',
    'pcBuilder.component.storage': 'التخزين',
    'pcBuilder.component.psu': 'مزود الطاقة',
    'pcBuilder.component.case': 'الكيس',
    'pcBuilder.component.cooler': 'المبرد',
    'pcBuilder.component.monitor': 'الشاشة',
    'pcBuilder.component.mouse': 'الماوس',
    'pcBuilder.component.keyboard': 'لوحة المفاتيح',
    'pcBuilder.select.cpu': 'اختر المعالج',
    'pcBuilder.select.motherboard': 'اختر اللوحة الأم',
    'pcBuilder.select.ram': 'اختر الذاكرة',
    'pcBuilder.select.gpu': 'اختر كرت الشاشة',
    'pcBuilder.select.storage': 'اختر التخزين',
    'pcBuilder.select.psu': 'اختر مزود الطاقة',
    'pcBuilder.select.case': 'اختر الكيس',
    'pcBuilder.select.cooler': 'اختر المبرد',
    'pcBuilder.select.monitor': 'اختر الشاشة',
    'pcBuilder.select.mouse': 'اختر الماوس',
    'pcBuilder.select.keyboard': 'اختر لوحة المفاتيح',
    'pcBuilder.selectDesc.cpu': 'اختر المعالج المناسب لاحتياجاتك',
    'pcBuilder.selectDesc.motherboard': 'اختر لوحة أم متوافقة مع المعالج',
    'pcBuilder.selectDesc.ram': 'اختر ذاكرة متوافقة مع اللوحة الأم',
    'pcBuilder.selectDesc.gpu': 'اختر كرت الشاشة المناسب للألعاب والعمل',
    'pcBuilder.selectDesc.storage': 'اختر نوع التخزين SSD أو HDD',
    'pcBuilder.selectDesc.psu': 'اختر مزود طاقة كافٍ لجميع المكونات',
    'pcBuilder.selectDesc.case': 'اختر كيس يناسب حجم المكونات',
    'pcBuilder.selectDesc.cooler': 'اختر مبرد للمعالج',
    'pcBuilder.selectDesc.monitor': 'اختر شاشة بالدقة والحجم المناسب',
    'pcBuilder.selectDesc.mouse': 'اختر ماوس مريح وبأداء عالي',
    'pcBuilder.selectDesc.keyboard': 'اختر لوحة مفاتيح مناسبة للعمل أو اللعب',
    'pcBuilder.compatibility.socketMismatch': 'المقبس غير متوافق مع المعالج',
    'pcBuilder.compatibility.ramTypeMismatch': 'نوع الذاكرة غير متوافق مع اللوحة الأم',
    'pcBuilder.compatibility.tooManyRamModules': 'عدد وحدات الذاكرة أكثر من المتاح',
    'pcBuilder.compatibility.gpuTooLong': 'كرت الشاشة طويل جداً للكيس',
    'pcBuilder.compatibility.coolerSocketMismatch': 'المبرد غير متوافق مع مقبس المعالج',
    'pcBuilder.compatibility.coolerTooTall': 'المبرد طويل جداً للكيس',
    'pcBuilder.compatibility.radiatorNotSupported': 'حجم المبرد المائي غير مدعوم',
    'pcBuilder.compatibility.caseFormFactorMismatch': 'الكيس لا يدعم حجم اللوحة الأم',
    'pcBuilder.compatibility.psuFormFactorMismatch': 'مزود الطاقة غير متوافق مع الكيس',
    
    // Common
    'common.currency': 'د.ع',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.ok': 'حسناً',
    'common.back': 'رجوع',
  },
  en: {
    // Header
    'header.title': 'Al-Ain Computer Trading',
    'header.home': 'Home',
    'header.categories': 'Categories',
    'header.cart': 'Cart',
    'header.login': 'Login',
    'header.profile': 'Profile',
    'header.logout': 'Logout',
    'header.searchPlaceholder': 'Search for products...',
    'header.search': 'Search',
    'header.searchTitle': 'Search',
    'header.searchDescription': 'Search for computers and accessories',
    'header.pcBuilder': 'Build Your PC',
    'header.marketAnalysis': 'Market Analysis',
    'header.trackOrder': 'Track Order',
    
    // Categories
    'category.all': 'All Products',
    'category.laptops': 'Laptops',
    'category.desktops': 'Desktops',
    'category.monitors': 'Monitors',
    'category.accessories': 'Accessories',
    'category.programs': 'Programs',
    
    // Home page
    'home.hero.title': 'Best Computers & Accessories',
    'home.hero.subtitle': 'Discover the latest technology at the best prices',
    'home.hero.cta': 'Shop Now',
    'home.categories.title': 'Browse by Category',
    'home.featured.title': 'Featured Products',
    'home.hero.imageAlt': 'Store promotional banner',
    'home.searchResultsFor': 'Search results for: {query}',
    'home.showAll': 'Show All',
    'home.noProducts': 'No products available',
    'home.noSearchResults': 'No products match your search',
    'home.requestProduct': 'Request this product',
    'home.requestProduct.title': 'Request Unavailable Product',
    'home.requestProduct.desc': 'Fill the form below and we will contact you when the product is available',
    'home.requestProduct.productName': 'Product name',
    'home.requestProduct.customerName': 'Your name',
    'home.requestProduct.customerPhone': 'Phone number',
    'home.requestProduct.customerEmail': 'Email (optional)',
    'home.requestProduct.notes': 'Additional notes',
    'home.requestProduct.submit': 'Submit Request',
    'home.requestProduct.success': 'Request submitted successfully! We will contact you soon',
    'home.requestProduct.error': 'Error submitting request',
    'home.loadError': 'An error occurred while loading products. Please try again.',
    'home.repair.title': 'Repair Service',
    'home.repair.subtitle': 'Does your device need repair?',
    'home.repair.description': 'We offer professional repair services for all types of computers and electronic devices. Our specialized team is ready to help you.',
    'home.repair.requestBtn': 'Request Repair',
    'home.repair.trackBtn': 'Track Your Request',
    'home.orderTracking.title': 'Track Your Order',
    'home.orderTracking.subtitle': 'Have an order on the way?',
    'home.orderTracking.description': 'Easily track your order status. Enter your order number and phone number to view shipping and delivery details.',
    'home.orderTracking.trackBtn': 'Track Order',
    
    // Customer Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.myOrders': 'My Orders',
    'dashboard.orderHistory': 'Order History',
    'dashboard.noOrders': 'No orders yet',
    'dashboard.noOrdersDesc': 'Start shopping now to see your orders here',
    'dashboard.startShopping': 'Start Shopping',
    'dashboard.orderNumber': 'Order Number',
    'dashboard.orderDate': 'Order Date',
    'dashboard.orderStatus': 'Status',
    'dashboard.orderTotal': 'Total',
    'dashboard.viewDetails': 'View Details',
    'dashboard.items': 'Items',
    'dashboard.shippingAddress': 'Shipping Address',
    'dashboard.paymentMethod': 'Payment Method',
    'dashboard.status.pending': 'Pending',
    'dashboard.status.confirmed': 'Confirmed',
    'dashboard.status.processing': 'Processing',
    'dashboard.status.shipped': 'Shipped',
    'dashboard.status.delivered': 'Delivered',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.loadError': 'Failed to load orders',
    'dashboard.loginRequired': 'Please login to view your orders',
    
    // Product
    'product.specifications': 'Specifications',
    'product.addToCart': 'Add to Cart',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.loading': 'Loading...',
    'product.notFound': 'Product not found',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.description': 'Manage your shopping cart items',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.browsProducts': 'Browse Products',
    'cart.remove': 'Remove',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.free': 'Free',
    'cart.quantity': 'Quantity',
    'cart.error': 'An error occurred while loading the cart',
    'cart.loginRequired': 'Login Required',
    'cart.loginRequiredDesc': 'Please login to add products to your shopping cart',
    'cart.addedToCart': 'Added to Cart',
    'cart.addedDescription': 'Product has been added to your cart',
    'cart.addError': 'An error occurred while adding the product',
    'cart.retry': 'Retry',
    'cart.removed': 'Removed',
    'cart.removedDescription': 'Product removed from cart',
    'cart.removeError': 'An error occurred while removing the product',
    'cart.quantityUpdateError': 'An error occurred while updating quantity',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.customerInfo': 'Delivery Information',
    'checkout.fullName': 'Full Name',
    'checkout.fullNamePlaceholder': 'Enter your full name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Detailed Address',
    'checkout.addressPlaceholder': 'Street, house number, nearest landmark',
    'checkout.governorate': 'Governorate',
    'checkout.selectGovernorate': 'Select governorate',
    'checkout.neighborhood': 'Neighborhood / Area',
    'checkout.neighborhoodPlaceholder': 'e.g., Karrada, Mansour',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.cashOnDeliveryDesc': 'Pay in cash when you receive your order',
    'checkout.zainCash': 'ZainCash',
    'checkout.zainCashDesc': 'Pay via ZainCash mobile wallet',
    'checkout.qiCard': 'QiCard',
    'checkout.qiCardDesc': 'Pay via QiCard bank card',
    'checkout.onlinePayment': 'Online Payment',
    'checkout.comingSoon': 'Coming Soon',
    'checkout.confirmOrder': 'Confirm Order',
    'checkout.processing': 'Processing order...',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Delivery',
    'checkout.freeShipping': 'Free',
    'checkout.freeShippingThreshold': 'Order {amount} IQD or more for free delivery',
    'checkout.orderSuccess': 'Order placed successfully!',
    'checkout.orderError': 'Failed to place order. Please try again.',
    'checkout.loading': 'Loading cart...',
    'checkout.addProductsFirst': 'Please add products before proceeding to checkout',
    'checkout.backToStore': 'Back to Store',
    
    // Order Confirmation
    'orderConfirmation.title': 'Order Confirmed!',
    'orderConfirmation.thankYou': 'Thank you for shopping with us',
    'orderConfirmation.orderNumber': 'Order Number',
    'orderConfirmation.orderDate': 'Order Date',
    'orderConfirmation.orderDetails': 'Order Details',
    'orderConfirmation.shippingInfo': 'Shipping Information',
    'orderConfirmation.paymentMethod': 'Payment Method',
    'orderConfirmation.orderItems': 'Ordered Products',
    'orderConfirmation.quantity': 'Quantity',
    'orderConfirmation.price': 'Price',
    'orderConfirmation.subtotal': 'Subtotal',
    'orderConfirmation.shipping': 'Shipping',
    'orderConfirmation.total': 'Total',
    'orderConfirmation.free': 'Free',
    'orderConfirmation.status': 'Order Status',
    'orderConfirmation.pending': 'Pending',
    'orderConfirmation.processing': 'Processing',
    'orderConfirmation.shipped': 'Shipped',
    'orderConfirmation.delivered': 'Delivered',
    'orderConfirmation.cancelled': 'Cancelled',
    'orderConfirmation.cashOnDelivery': 'Cash on Delivery',
    'orderConfirmation.zainCash': 'ZainCash',
    'orderConfirmation.qiCard': 'QiCard',
    'orderConfirmation.continueShopping': 'Continue Shopping',
    'orderConfirmation.loading': 'Loading order details...',
    'orderConfirmation.notFound': 'Order not found',
    'orderConfirmation.emailSent': 'Order confirmation has been sent to your email',
    'orderConfirmation.contactSoon': 'We will contact you soon to confirm your order',
    
    // Order Tracking
    'orderTracking.title': 'Track Your Order',
    'orderTracking.description': 'Enter your order number and phone number to check your order status',
    'orderTracking.orderNumber': 'Order Number',
    'orderTracking.orderNumberPlaceholder': 'ORD-01001',
    'orderTracking.phone': 'Phone Number',
    'orderTracking.phonePlaceholder': '07XXXXXXXXX',
    'orderTracking.phoneHint': 'The phone number used when ordering',
    'orderTracking.submit': 'Track Order',
    'orderTracking.searching': 'Searching...',
    'orderTracking.notFound': 'Order Not Found',
    'orderTracking.notFoundDesc': 'Please verify the order number and phone number',
    'orderTracking.invalidFormat': 'Invalid Format',
    'orderTracking.invalidOrderNumber': 'Order number must be in ORD-XXXXX format',
    'orderTracking.invalidPhone': 'Phone number must start with 07 and be 11 digits',
    'orderTracking.orderDetails': 'Order Details',
    'orderTracking.backToHome': 'Back to Home',
    'orderTracking.trackAnother': 'Track Another Order',
    
    // Login
    'login.title': 'Login',
    'login.description': 'Enter your email and password, then the verification code sent to your inbox',
    'login.otpTitle': 'Verification code',
    'login.otpDescription': 'Enter the code sent to your email ({email})',
    'login.otpLabel': 'Verification code (6 digits)',
    'login.otpPlaceholder': '••••••',
    'login.verifyOtp': 'Verify and sign in',
    'login.backToCredentials': 'Back',
    'login.forgotPassword': 'Forgot password?',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Create Account',
    'login.loggingIn': 'Logging in...',
    'login.success.title': 'Login successful',
    'login.success.description': 'Welcome back',
    'login.error.title': 'Login error',
    'login.error.description': 'Invalid email or password',
    'login.backToHome': 'Back to Home',
    'forgot.title': 'Reset password',
    'forgot.description': 'Enter your email to receive a verification code',
    'forgot.sendCode': 'Send code',
    'forgot.step2': 'Enter the code and your new password',
    'forgot.newPassword': 'New password',
    'forgot.confirmPassword': 'Confirm password',
    'forgot.reset': 'Update password',
    'forgot.backToLogin': 'Back to login',
    'forgot.mismatch': 'Passwords do not match',
    'forgot.descriptionSent': 'If the email is registered, you will receive a code shortly.',
    'change.title': 'Change password',
    'change.current': 'Current password',
    'change.new': 'New password',
    'change.confirm': 'Confirm new password',
    'change.submit': 'Save',
    'change.success': 'Password updated',
    'change.mismatch': 'New passwords do not match',
    
    // Register
    'register.title': 'Create New Account',
    'register.description': 'Create your account to start shopping',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.passwordHint': 'Must be at least 6 characters',
    'register.submit': 'Create Account',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.registering': 'Creating account...',
    'register.success.title': 'Account created successfully',
    'register.success.description': 'Welcome to Al-Ain Computer Trading',
    'register.error.title': 'Error creating account',
    'register.error.description': 'An error occurred, please try again',
    'register.backToHome': 'Back to Home',
    
    // Admin
    'admin.login.title': 'Admin Login',
    'admin.login.password': 'Password',
    'admin.login.submit': 'Login',
    'admin.dashboard.title': 'Dashboard',
    'admin.dashboard.ordersTitle': 'Order Management',
    'admin.dashboard.ordersCount': 'Order Count',
    'admin.dashboard.noOrders': 'No orders currently',
    'admin.dashboard.orders': 'Orders',
    'admin.dashboard.orderNumber': 'Order #',
    'admin.dashboard.customer': 'Customer',
    'admin.dashboard.email': 'Email',
    'admin.dashboard.phone': 'Phone',
    'admin.dashboard.city': 'City',
    'admin.dashboard.itemsCount': 'Items Count',
    'admin.dashboard.item': 'item',
    'admin.dashboard.total': 'Total',
    'admin.dashboard.status': 'Status',
    'admin.dashboard.date': 'Date',
    'admin.dashboard.update': 'Update',
    'admin.dashboard.updating': 'Updating...',
    'admin.dashboard.logout': 'Logout',
    'admin.dashboard.pending': 'Pending',
    'admin.dashboard.processing': 'Processing',
    'admin.dashboard.shipped': 'Shipped',
    'admin.dashboard.delivered': 'Delivered',
    'admin.dashboard.cancelled': 'Cancelled',
    'admin.dashboard.updateSuccess': 'Update Successful',
    'admin.dashboard.updateSuccessDesc': 'Order status updated',
    'admin.dashboard.delete': 'Delete',
    'admin.dashboard.deleting': 'Deleting...',
    'admin.dashboard.deleteOrderTitle': 'Delete Order',
    'admin.dashboard.deleteOrderConfirm': 'Are you sure you want to delete this order? This action cannot be undone.',
    'admin.dashboard.deleteSuccess': 'Deleted Successfully',
    'admin.dashboard.deleteSuccessDesc': 'Order has been deleted',
    'admin.dashboard.deleteError': 'Error',
    'admin.dashboard.deleteErrorDesc': 'Failed to delete order',
    'admin.dashboard.updateError': 'Error',
    'admin.dashboard.updateErrorDesc': 'Failed to update order',
    'admin.dashboard.logoutSuccess': 'Logged Out',
    'admin.dashboard.logoutSuccessDesc': 'You have been logged out successfully',
    
    // Admin Notifications
    'admin.notifications.title': 'Notifications',
    'admin.notifications.empty': 'No new notifications',
    'admin.notifications.newOrder': 'New Order',
    'admin.notifications.markAllRead': 'Mark all read',
    
    // Admin Products
    'admin.products.title': 'Manage Products',
    'admin.products.addNew': 'Add New Product',
    'admin.products.edit': 'Edit',
    'admin.products.delete': 'Delete',
    'admin.products.confirmDelete': 'Are you sure you want to delete this product?',
    'admin.products.nameAr': 'Arabic Name',
    'admin.products.nameEn': 'English Name',
    'admin.products.descAr': 'Arabic Description',
    'admin.products.descEn': 'English Description',
    'admin.products.price': 'Price',
    'admin.products.oldPrice': 'Old Price',
    'admin.products.category': 'Category',
    'admin.products.image': 'Image URL',
    'admin.products.badge': 'Badge',
    'admin.products.inStock': 'In Stock',
    'admin.products.specs': 'Specifications (one per line)',
    'admin.products.save': 'Save',
    'admin.products.cancel': 'Cancel',
    'admin.products.creating': 'Creating...',
    'admin.products.updating': 'Updating...',
    'admin.products.deleting': 'Deleting...',
    'admin.products.actions': 'Actions',
    'admin.products.manageProducts': 'Manage Products',
    'admin.products.imagePlaceholder': 'product_image.png',
    
    // Admin Customers
    'admin.customers.title': 'Manage Customers',
    'admin.customers.subtitle': 'View and manage customer accounts',
    'admin.customers.manageCustomers': 'Manage Customers',
    'admin.customers.noCustomers': 'No registered customers',
    'admin.customers.noCustomersDesc': 'Customers will appear here after they register',
    'admin.customers.backToDashboard': 'Back to Dashboard',
    'admin.customers.name': 'Name',
    'admin.customers.email': 'Email',
    'admin.customers.phone': 'Phone',
    'admin.customers.registeredAt': 'Registered At',
    'admin.customers.ordersCount': 'Orders Count',
    'admin.customers.totalSpent': 'Total Spent',
    'admin.customers.actions': 'Actions',
    'admin.customers.view': 'View',
    'admin.customers.edit': 'Edit',
    'admin.customers.delete': 'Delete',
    'admin.customers.editCustomer': 'Edit Customer',
    'admin.customers.viewCustomer': 'View Customer',
    'admin.customers.deleteTitle': 'Delete Customer',
    'admin.customers.confirmDelete': 'Are you sure you want to delete this customer? This action cannot be undone.',
    'admin.customers.cancel': 'Cancel',
    'admin.customers.save': 'Save',
    'admin.customers.updating': 'Updating...',
    'admin.customers.deleting': 'Deleting...',
    'admin.customers.password': 'New Password',
    'admin.customers.passwordHint': 'Leave empty to keep unchanged',
    'admin.customers.updateSuccess': 'Customer updated successfully',
    'admin.customers.updateError': 'Failed to update customer',
    'admin.customers.deleteSuccess': 'Customer deleted successfully',
    'admin.customers.deleteError': 'Failed to delete customer',
    'admin.customers.customersCount': 'Customers Count',
    
    // Admin Programs
    'admin.programs.title': 'Manage Programs',
    'admin.programs.subtitle': 'Add and edit software programs',
    'admin.programs.managePrograms': 'Manage Programs',
    'admin.programs.addNew': 'Add New Program',
    'admin.programs.editProgram': 'Edit Program',
    'admin.programs.noPrograms': 'No Programs',
    'admin.programs.noProgramsDesc': 'Start by adding your first program',
    'admin.programs.addFirst': 'Add First Program',
    'admin.programs.backToDashboard': 'Back to Dashboard',
    'admin.programs.nameAr': 'Program Name (Arabic)',
    'admin.programs.nameEn': 'Program Name (English)',
    'admin.programs.nameArPlaceholder': 'e.g., Microsoft Office',
    'admin.programs.nameEnPlaceholder': 'e.g., Microsoft Office',
    'admin.programs.descAr': 'Description (Arabic)',
    'admin.programs.descEn': 'Description (English)',
    'admin.programs.descArPlaceholder': 'Detailed program description...',
    'admin.programs.descEnPlaceholder': 'Detailed program description...',
    'admin.programs.licenseType': 'License Type',
    'admin.programs.licenseTypePlaceholder': 'e.g., Annual, Lifetime, Monthly',
    'admin.programs.version': 'Version',
    'admin.programs.versionPlaceholder': 'e.g., 2024, v1.0',
    'admin.programs.price': 'Price',
    'admin.programs.oldPrice': 'Old Price',
    'admin.programs.stockQuantity': 'Quantity',
    'admin.programs.imageUrl': 'Image URL',
    'admin.programs.imageUrlPlaceholder': 'https://example.com/image.png',
    'admin.programs.badge': 'Badge',
    'admin.programs.badgePlaceholder': 'e.g., New, Sale',
    'admin.programs.features': 'Features',
    'admin.programs.featuresPlaceholder': 'Enter each feature on a new line...',
    'admin.programs.inStock': 'Availability',
    'admin.programs.available': 'Available',
    'admin.programs.unavailable': 'Unavailable',
    'admin.programs.image': 'Image',
    'admin.programs.actions': 'Actions',
    'admin.programs.edit': 'Edit',
    'admin.programs.delete': 'Delete',
    'admin.programs.deleteTitle': 'Delete Program',
    'admin.programs.confirmDelete': 'Are you sure you want to delete this program? This action cannot be undone.',
    'admin.programs.cancel': 'Cancel',
    'admin.programs.save': 'Save',
    'admin.programs.creating': 'Creating...',
    'admin.programs.updating': 'Updating...',
    'admin.programs.deleting': 'Deleting...',
    
    // Admin Settings
    'admin.settings.title': 'Store Settings',
    'admin.settings.storeInfo': 'Store Information',
    'admin.settings.storeInfoDesc': 'Update your store name and description',
    'admin.settings.contactInfo': 'Contact Information',
    'admin.settings.contactInfoDesc': 'Update email, phone, and location',
    'admin.settings.socialMedia': 'Social Media',
    'admin.settings.socialMediaDesc': 'Add your social media profile links',
    'admin.settings.storeNameAr': 'Store Name (Arabic)',
    'admin.settings.storeNameEn': 'Store Name (English)',
    'admin.settings.descriptionAr': 'Description (Arabic)',
    'admin.settings.descriptionEn': 'Description (English)',
    'admin.settings.email': 'Email Address',
    'admin.settings.phone': 'Phone Number',
    'admin.settings.phoneAr': 'Phone Number (Arabic)',
    'admin.settings.addressAr': 'Address (Arabic)',
    'admin.settings.addressEn': 'Address (English)',
    'admin.settings.hoursAr': 'Working Hours (Arabic)',
    'admin.settings.hoursEn': 'Working Hours (English)',
    'admin.settings.facebookUrl': 'Facebook URL',
    'admin.settings.twitterUrl': 'Twitter URL',
    'admin.settings.instagramUrl': 'Instagram URL',
    'admin.settings.whatsappNumber': 'WhatsApp Number',
    'admin.settings.whatsappNumberHint': 'Phone number (e.g., 07701234567)',
    'admin.settings.save': 'Save Settings',
    'admin.settings.successTitle': 'Saved',
    'admin.settings.successMessage': 'Store settings saved successfully',
    'admin.settings.errorMessage': 'Failed to save settings',
    'admin.settings.manageSettings': 'Store Settings',
    'admin.settings.validation.storeNameArRequired': 'Store name in Arabic is required',
    'admin.settings.validation.storeNameEnRequired': 'Store name in English is required',
    'admin.settings.validation.descriptionArRequired': 'Description in Arabic is required',
    'admin.settings.validation.descriptionEnRequired': 'Description in English is required',
    'admin.settings.validation.emailInvalid': 'Invalid email address',
    'admin.settings.validation.phoneRequired': 'Phone number is required',
    'admin.settings.validation.phoneArRequired': 'Phone number in Arabic is required',
    'admin.settings.validation.addressArRequired': 'Address in Arabic is required',
    'admin.settings.validation.addressEnRequired': 'Address in English is required',
    'admin.settings.validation.hoursArRequired': 'Working hours in Arabic are required',
    'admin.settings.validation.hoursEnRequired': 'Working hours in English are required',
    
    // Admin Settings Tabs
    'admin.settings.tabs.store': 'Store',
    'admin.settings.tabs.theme': 'Theme',
    'admin.settings.tabs.seo': 'SEO',
    'admin.settings.tabs.homepage': 'Homepage',
    'admin.settings.tabs.footer': 'Footer',
    'admin.settings.tabs.shipping': 'Shipping & Payment',
    
    // Theme Settings
    'admin.settings.theme.branding': 'Branding',
    'admin.settings.theme.brandingDesc': 'Upload your store logo and favicon',
    'admin.settings.theme.logoUrl': 'Logo URL',
    'admin.settings.theme.logoUrlHint': 'URL to your store logo image',
    'admin.settings.theme.faviconUrl': 'Favicon URL',
    'admin.settings.theme.faviconUrlHint': 'URL to your store favicon',
    'admin.settings.theme.colors': 'Colors',
    'admin.settings.theme.colorsDesc': 'Choose your store primary colors',
    'admin.settings.theme.primaryColor': 'Primary Color',
    'admin.settings.theme.accentColor': 'Accent Color',
    'admin.settings.theme.currency': 'Currency',
    'admin.settings.theme.currencyDesc': 'Currency display settings',
    'admin.settings.theme.currencySymbolAr': 'Currency Symbol (Arabic)',
    'admin.settings.theme.currencySymbolEn': 'Currency Symbol (English)',
    
    // SEO Settings
    'admin.settings.seo.metaTitle': 'Page Title',
    'admin.settings.seo.metaTitleDesc': 'Title that appears in search results',
    'admin.settings.seo.metaTitleAr': 'Page Title (Arabic)',
    'admin.settings.seo.metaTitleEn': 'Page Title (English)',
    'admin.settings.seo.metaDescription': 'Page Description',
    'admin.settings.seo.metaDescriptionDesc': 'Description that appears in search results',
    'admin.settings.seo.metaDescriptionAr': 'Page Description (Arabic)',
    'admin.settings.seo.metaDescriptionEn': 'Page Description (English)',
    'admin.settings.seo.keywords': 'Keywords',
    'admin.settings.seo.keywordsDesc': 'Keywords for search engines',
    'admin.settings.seo.keywordsAr': 'Keywords (Arabic)',
    'admin.settings.seo.keywordsEn': 'Keywords (English)',
    'admin.settings.seo.keywordsPlaceholder': 'keyword1, keyword2, keyword3',
    
    // Homepage Settings
    'admin.settings.homepage.announcement': 'Announcement Bar',
    'admin.settings.homepage.announcementDesc': 'Settings for the offers and announcements bar at the top of the page',
    'admin.settings.homepage.enableAnnouncement': 'Enable Announcement Bar',
    'admin.settings.homepage.announcementTextAr': 'Announcement Text (Arabic)',
    'admin.settings.homepage.announcementTextEn': 'Announcement Text (English)',
    'admin.settings.homepage.announcementPlaceholder': 'Example: 20% off all products!',
    'admin.settings.homepage.announcementBgColor': 'Background Color',
    'admin.settings.homepage.dismissCount': 'Dismiss Count',
    'admin.settings.homepage.resetCount': 'Reset',
    'admin.settings.homepage.dismissCountReset': 'Count Reset',
    'admin.settings.homepage.dismissCountResetDesc': 'Dismiss count has been reset to zero',
    'admin.settings.homepage.scrollDirection': 'Scroll Direction',
    'admin.settings.homepage.scrollRtl': 'Right to Left',
    'admin.settings.homepage.scrollLtr': 'Left to Right',
    'admin.settings.homepage.hero': 'Hero Banner',
    'admin.settings.homepage.heroDesc': 'Homepage hero banner settings',
    'admin.settings.homepage.showHeroBanner': 'Show Hero Banner',
    'admin.settings.homepage.heroTitleAr': 'Hero Title (Arabic)',
    'admin.settings.homepage.heroTitleEn': 'Hero Title (English)',
    'admin.settings.homepage.heroSubtitleAr': 'Hero Subtitle (Arabic)',
    'admin.settings.homepage.heroSubtitleEn': 'Hero Subtitle (English)',
    'admin.settings.homepage.heroImageUrl': 'Hero Image URL',
    'admin.settings.homepage.heroImageHint': 'Recommended size: 1920x600 pixels',
    'admin.settings.homepage.sections': 'Homepage Sections',
    'admin.settings.homepage.sectionsDesc': 'Control which sections are displayed',
    'admin.settings.homepage.showCategories': 'Show Categories Section',
    'admin.settings.homepage.showFeaturedProducts': 'Show Featured Products',
    'admin.settings.homepage.featuredProductsCount': 'Number of Featured Products',
    
    // Footer Settings
    'admin.settings.footer.about': 'About Text',
    'admin.settings.footer.aboutDesc': 'Text displayed in the footer',
    'admin.settings.footer.aboutTextAr': 'About Text (Arabic)',
    'admin.settings.footer.aboutTextEn': 'About Text (English)',
    'admin.settings.footer.copyright': 'Copyright',
    'admin.settings.footer.copyrightDesc': 'Copyright text in footer',
    'admin.settings.footer.copyrightTextAr': 'Copyright Text (Arabic)',
    'admin.settings.footer.copyrightTextEn': 'Copyright Text (English)',
    'admin.settings.footer.linksTitle': 'Footer Links',
    'admin.settings.footer.linksDesc': 'Manage link groups in the footer',
    'admin.settings.footer.noGroups': 'No link groups. Add a new group to get started.',
    'admin.settings.footer.untitledGroup': 'Untitled Group',
    'admin.settings.footer.links': 'links',
    'admin.settings.footer.groupTitleAr': 'Group Title (Arabic)',
    'admin.settings.footer.groupTitleEn': 'Group Title (English)',
    'admin.settings.footer.groupTitlePlaceholder': 'Enter group title',
    'admin.settings.footer.linksInGroup': 'Links in this group',
    'admin.settings.footer.noLinks': 'No links in this group',
    'admin.settings.footer.labelAr': 'Label (Arabic)',
    'admin.settings.footer.labelEn': 'Label (English)',
    'admin.settings.footer.labelPlaceholder': 'Link text',
    'admin.settings.footer.url': 'URL',
    'admin.settings.footer.external': 'External link',
    'admin.settings.footer.addLink': 'Add Link',
    'admin.settings.footer.addGroup': 'Add Link Group',
    'admin.settings.footer.removeGroup': 'Remove Group',
    
    // Shipping Settings
    'admin.settings.shipping.title': 'Shipping Settings',
    'admin.settings.shipping.description': 'Manage shipping and delivery costs',
    'admin.settings.shipping.cost': 'Shipping Cost',
    'admin.settings.shipping.costHint': 'Shipping cost in Iraqi Dinar',
    'admin.settings.shipping.freeThreshold': 'Free Shipping Threshold',
    'admin.settings.shipping.freeThresholdHint': 'Minimum order amount for free shipping',
    'admin.settings.shipping.enableFreeShipping': 'Enable Free Shipping',
    
    // Payment Settings
    'admin.settings.payment.title': 'Payment Methods',
    'admin.settings.payment.description': 'Manage available payment methods',
    'admin.settings.payment.cashOnDelivery': 'Cash on Delivery',
    'admin.settings.payment.electronicPayment': 'Electronic Payment',
    
    // Categories
    'categories.laptops': 'Laptops',
    'categories.desktops': 'Desktops',
    'categories.monitors': 'Monitors',
    'categories.accessories': 'Accessories',
    
    // Footer
    'footer.about': 'About',
    'footer.defaultStoreName': 'Al-Ain Computer Trading',
    'footer.defaultDescription': 'Your trusted store for the latest computers and accessories at the best prices and highest quality',
    'footer.email': 'Email:',
    'footer.phone': 'Phone:',
    'footer.hours': 'Working Hours:',
    'footer.defaultEmail': 'info@alain-computers.com',
    'footer.defaultPhone': '920001234',
    'footer.defaultHours': 'Saturday - Thursday 9am - 9pm',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact Us',
    'footer.branches': 'Our Branches',
    'footer.careers': 'Careers',
    'footer.customerService': 'Customer Service',
    'footer.shipping': 'Shipping Policy',
    'footer.returns': 'Returns & Exchanges',
    'footer.warranty': 'Warranty',
    'footer.faq': 'FAQ',
    'footer.trackOrder': 'Track Your Order',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.newsletterDesc': 'Get the latest offers and news',
    'footer.newsletterPlaceholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.followUs': 'Follow Us',
    'footer.whatsapp': 'Contact us on WhatsApp',
    'footer.location': 'Our Location',
    'footer.copyright': '© 2025 Al-Ain Computer Trading. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    
    // Repair Tracking
    'repair.request.title': 'Repair Request',
    'repair.request.description': 'Submit your device for repair',
    'repair.request.customerInfo': 'Customer Information',
    'repair.request.deviceInfo': 'Device Information',
    'repair.request.customerName': 'Full Name',
    'repair.request.customerPhone': 'Phone Number',
    'repair.request.customerEmail': 'Email (Optional)',
    'repair.request.deviceType': 'Device Type',
    'repair.request.deviceBrand': 'Brand',
    'repair.request.deviceModel': 'Model',
    'repair.request.issueDescription': 'Issue Description',
    'repair.request.issueDescriptionPlaceholder': 'Describe the issue in detail...',
    'repair.request.issueDescriptionNote': 'Please describe the issue in detail for a better estimate',
    'repair.request.submit': 'Submit Repair Request',
    'repair.request.submitting': 'Submitting...',
    'repair.request.successTitle': 'Request Submitted',
    'repair.request.successMessage': 'Ticket Number: {ticketNumber}',
    'repair.request.successNote': 'Save this ticket number to track your repair status',
    'repair.request.copyTicket': 'Copy Ticket Number',
    'repair.request.copied': 'Copied',
    'repair.request.errorTitle': 'Request Failed',
    'repair.request.errorMessage': 'An error occurred, please try again',
    
    'repair.lookup.title': 'Track Repair',
    'repair.lookup.description': 'Check your repair request status',
    'repair.lookup.phonePlaceholder': '07901234567',
    'repair.lookup.ticketNumber': 'Ticket Number',
    'repair.lookup.ticketNumberPlaceholder': 'AEEN-00001',
    'repair.lookup.searchPlaceholder': 'Ticket number, phone number, or receipt number',
    'repair.lookup.searchHint': 'Search by ticket number (e.g. AEEN-00001), phone number, or receipt number',
    'repair.lookup.search': 'Search',
    'repair.lookup.searching': 'Searching...',
    'repair.lookup.notFound': 'No results found. Please check your ticket number, phone number, or receipt number',
    'repair.lookup.errorMessage': 'An error occurred while searching',
    
    'repair.ticket.details': 'Ticket Details',
    'repair.ticket.ticketNumber': 'Ticket Number',
    'repair.ticket.status': 'Status',
    'repair.ticket.priority': 'Priority',
    'repair.ticket.createdAt': 'Created At',
    'repair.ticket.updatedAt': 'Last Updated',
    'repair.ticket.estimatedCompletion': 'Estimated Completion',
    'repair.ticket.costEstimate': 'Estimated Cost',
    'repair.ticket.finalCost': 'Final Cost',
    'repair.ticket.technicianNotes': 'Technician Notes',
    'repair.ticket.customerName': 'Customer Name',
    'repair.ticket.customerPhone': 'Customer Phone',
    'repair.ticket.customerEmail': 'Customer Email',
    'repair.ticket.deviceType': 'Device Type',
    'repair.ticket.deviceBrand': 'Brand',
    'repair.ticket.deviceModel': 'Model',
    'repair.ticket.issueDescription': 'Issue Description',
    
    'repair.status.pending': 'Pending',
    'repair.status.in-progress': 'In Progress',
    'repair.status.waiting-parts': 'Waiting for Parts',
    'repair.status.completed': 'Completed',
    'repair.status.delivered': 'Delivered',
    'repair.status.rejected': 'Repair Rejected',
    'repair.status.unrepairable': 'Unrepairable',
    
    'repair.priority.low': 'Low',
    'repair.priority.normal': 'Normal',
    'repair.priority.high': 'High',
    'repair.priority.urgent': 'Urgent',
    'repair.priority.vip': 'VIP',

    'repair.payment.unpaid': 'Unpaid',
    'repair.payment.paid': 'Paid',
    'repair.payment.deferred': 'Deferred',
    'repair.ticket.paymentStatus': 'Payment Status',

    'repair.deviceType.laptop': 'Laptop',
    'repair.deviceType.desktop': 'Desktop',
    'repair.deviceType.monitor': 'Monitor',
    'repair.deviceType.printer': 'Printer',
    'repair.deviceType.other': 'Other',
    
    'repair.technician.login.title': 'Technician Login',
    'repair.technician.login.description': 'Enter your password to access the technician dashboard',
    'repair.technician.login.password': 'Password',
    'repair.technician.login.passwordPlaceholder': 'Enter password',
    'repair.technician.login.submit': 'Login',
    'repair.technician.login.successTitle': 'Logged In',
    'repair.technician.login.successDescription': 'Welcome back',
    'repair.technician.login.errorTitle': 'Error',
    'repair.technician.login.errorDescription': 'Incorrect password',
    
    // Technician Login (with username/password)
    'technician.login.title': 'Repair System',
    'technician.login.description': 'Sign in to access the repair management system',
    'technician.login.username': 'Username',
    'technician.login.usernamePlaceholder': 'Enter your username',
    'technician.login.password': 'Password',
    'technician.login.passwordPlaceholder': 'Enter your password',
    'technician.login.submit': 'Sign In',
    'technician.login.loggingIn': 'Signing in...',
    'technician.login.backToHome': 'Back to Home',
    'technician.login.success.title': 'Logged in successfully',
    'technician.login.success.description': 'Welcome to the repair system',
    'technician.login.error.title': 'Login Error',
    'technician.login.error.description': 'Invalid username or password',
    
    // Technician Management
    'technician.management.title': 'Technician Management',
    'technician.management.addNew': 'Add Technician',
    'technician.management.edit': 'Edit',
    'technician.management.delete': 'Delete',
    'technician.management.username': 'Username',
    'technician.management.displayName': 'Display Name',
    'technician.management.password': 'Password',
    'technician.management.newPassword': 'New Password',
    'technician.management.isAdmin': 'Admin Privileges',
    'technician.management.isActive': 'Status',
    'technician.management.active': 'Active',
    'technician.management.inactive': 'Disabled',
    'technician.management.permissions': 'Permissions',
    'technician.management.permission.view_tickets': 'View Tickets',
    'technician.management.permission.update_status': 'Update Status',
    'technician.management.permission.manage_tickets': 'Manage Tickets',
    'technician.management.permission.manage_technicians': 'Manage Technicians',
    'technician.management.permission.view_revenue': 'View Revenue',
    'technician.management.permission.view_daily_report': 'Repair Report',
    'technician.management.confirmDelete': 'Are you sure you want to delete this technician?',
    'technician.management.deleted': 'Technician deleted successfully',
    'technician.management.created': 'Technician created successfully',
    'technician.management.updated': 'Technician updated successfully',
    'technician.management.noTechnicians': 'No technicians found',
    'technician.management.leaveBlankPassword': 'Leave blank to keep current password',
    
    // Technician Dashboard
    'technician.dashboard.logout': 'Sign Out',
    'technician.dashboard.welcome': 'Welcome, {name}',
    'repair.technician.dashboard.title': 'Technician Dashboard',
    'repair.technician.dashboard.allTickets': 'All Tickets',
    'repair.technician.dashboard.newTicket': 'New Ticket',
    'repair.technician.dashboard.filterStatus': 'Filter by Status',
    'repair.technician.dashboard.filterPriority': 'Filter by Priority',
    'repair.technician.dashboard.searchPhone': 'Search by phone number...',
    'repair.technician.dashboard.searchNameOrPhone': 'Search by name or phone...',
    'repair.technician.dashboard.searchAll': 'Search by name, phone, or ticket #...',
    'repair.technician.dashboard.noTickets': 'No tickets found',
    'repair.whatsapp.dashboardButton': 'WhatsApp — all completed',
    'repair.whatsapp.confirmTitle': 'Confirm WhatsApp send',
    'repair.whatsapp.confirmDescription': 'Send the ready-for-pickup message to customers for {count} completed ticket(s)?',
    'repair.whatsapp.confirmSend': 'Send',
    'repair.whatsapp.confirmCancel': 'Cancel',
    'repair.whatsapp.bulkResult': 'Sent {sent} of {total}',
    
    'repair.edit.title': 'Update Ticket',
    'repair.edit.updateStatus': 'Update Status',
    'repair.edit.updatePriority': 'Update Priority',
    'repair.edit.addNotes': 'Add Notes',
    'repair.edit.setEstimatedCompletion': 'Set Estimated Completion',
    'repair.edit.setCostEstimate': 'Set Estimated Cost',
    'repair.edit.setFinalCost': 'Set Final Cost',
    'repair.edit.save': 'Save Changes',
    'repair.edit.saving': 'Saving...',
    'repair.edit.successTitle': 'Updated',
    'repair.edit.successMessage': 'Ticket updated successfully',
    'repair.edit.errorMessage': 'Failed to update ticket',
    
    'repair.delete.button': 'Delete Ticket',
    'repair.delete.title': 'Delete Ticket',
    'repair.delete.description': 'Are you sure you want to delete this ticket? This action cannot be undone.',
    'repair.delete.confirm': 'Yes, Delete',
    'repair.delete.cancel': 'Cancel',
    'repair.delete.deleting': 'Deleting...',
    'repair.delete.successTitle': 'Deleted',
    'repair.delete.successMessage': 'Ticket deleted successfully',
    'repair.delete.errorMessage': 'Failed to delete ticket',
    
    // PC Builder
    'pcBuilder.title': 'PC Builder',
    'pcBuilder.subtitle': 'Select components and build your perfect PC',
    'pcBuilder.backToStore': 'Back to Store',
    'pcBuilder.yourBuild': 'Your Build',
    'pcBuilder.selectedParts': '{{count}} parts selected',
    'pcBuilder.notSelected': 'Not selected',
    'pcBuilder.selected': 'Selected',
    'pcBuilder.total': 'Total',
    'pcBuilder.addToCart': 'Add to Cart',
    'pcBuilder.clearBuild': 'Clear All',
    'pcBuilder.estimatedPower': 'Estimated Power',
    'pcBuilder.recommendedPsu': 'Recommended PSU',
    'pcBuilder.psuInsufficient': 'PSU insufficient for this build',
    'pcBuilder.noComponents': 'No components available',
    'pcBuilder.previousStep': 'Previous',
    'pcBuilder.nextStep': 'Next',
    'pcBuilder.addedToCart': 'Added to Cart',
    'pcBuilder.addedToCartDesc': 'All components have been added to your cart',
    'pcBuilder.addToCartError': 'Failed to add components to cart',
    'pcBuilder.component.cpu': 'CPU',
    'pcBuilder.component.motherboard': 'Motherboard',
    'pcBuilder.component.ram': 'RAM',
    'pcBuilder.component.gpu': 'Graphics Card',
    'pcBuilder.component.storage': 'Storage',
    'pcBuilder.component.psu': 'Power Supply',
    'pcBuilder.component.case': 'Case',
    'pcBuilder.component.cooler': 'CPU Cooler',
    'pcBuilder.select.cpu': 'Select CPU',
    'pcBuilder.select.motherboard': 'Select Motherboard',
    'pcBuilder.select.ram': 'Select RAM',
    'pcBuilder.select.gpu': 'Select Graphics Card',
    'pcBuilder.select.storage': 'Select Storage',
    'pcBuilder.select.psu': 'Select Power Supply',
    'pcBuilder.select.case': 'Select Case',
    'pcBuilder.select.cooler': 'Select CPU Cooler',
    'pcBuilder.selectDesc.cpu': 'Choose the right processor for your needs',
    'pcBuilder.selectDesc.motherboard': 'Choose a motherboard compatible with your CPU',
    'pcBuilder.selectDesc.ram': 'Choose RAM compatible with your motherboard',
    'pcBuilder.selectDesc.gpu': 'Choose a graphics card for gaming and work',
    'pcBuilder.selectDesc.storage': 'Choose SSD or HDD storage',
    'pcBuilder.selectDesc.psu': 'Choose a power supply sufficient for all components',
    'pcBuilder.selectDesc.case': 'Choose a case that fits your components',
    'pcBuilder.selectDesc.cooler': 'Choose a cooler for your CPU',
    'pcBuilder.compatibility.socketMismatch': 'Socket incompatible with CPU',
    'pcBuilder.compatibility.ramTypeMismatch': 'RAM type incompatible with motherboard',
    'pcBuilder.compatibility.tooManyRamModules': 'Too many RAM modules for motherboard',
    'pcBuilder.compatibility.gpuTooLong': 'Graphics card too long for case',
    'pcBuilder.compatibility.coolerSocketMismatch': 'Cooler incompatible with CPU socket',
    'pcBuilder.compatibility.coolerTooTall': 'Cooler too tall for case',
    'pcBuilder.compatibility.radiatorNotSupported': 'Radiator size not supported by case',
    'pcBuilder.compatibility.caseFormFactorMismatch': 'Case does not support motherboard form factor',
    'pcBuilder.compatibility.psuFormFactorMismatch': 'PSU form factor incompatible with case',
    
    // Common
    'common.currency': 'IQD',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.ok': 'OK',
    'common.back': 'Back',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'ar') ? saved : 'ar';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, vars?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    if (vars) {
      Object.entries(vars).forEach(([varKey, value]) => {
        text = text.replace(`{${varKey}}`, value);
      });
    }
    return text;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
