import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string, vars?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Header
    'header.title': 'العين لتجارة الحاسبات',
    'header.home': 'الرئيسية',
    'header.categories': 'الفئات',
    'header.cart': 'السلة',
    'header.login': 'تسجيل الدخول',
    'header.profile': 'الملف الشخصي',
    'header.logout': 'تسجيل الخروج',
    'header.searchPlaceholder': 'ابحث عن المنتجات...',
    'header.searchTitle': 'البحث',
    'header.searchDescription': 'ابحث عن منتجات الحواسيب والملحقات',
    
    // Categories
    'category.all': 'جميع المنتجات',
    'category.laptops': 'أجهزة لابتوب',
    'category.desktops': 'أجهزة مكتبية',
    'category.monitors': 'شاشات',
    'category.accessories': 'ملحقات',
    
    // Home page
    'home.hero.title': 'أفضل أجهزة الحاسوب والملحقات',
    'home.hero.subtitle': 'اكتشف أحدث التقنيات بأفضل الأسعار',
    'home.hero.cta': 'تسوق الآن',
    'home.hero.imageAlt': 'صورة إعلانية للمتجر',
    'home.categories.title': 'تصفح حسب الفئة',
    'home.featured.title': 'المنتجات المميزة',
    'home.searchResultsFor': 'نتائج البحث عن: {query}',
    'home.showAll': 'عرض الكل',
    'home.noProducts': 'لا توجد منتجات متاحة',
    'home.noSearchResults': 'لا توجد منتجات تطابق البحث',
    'home.loadError': 'حدث خطأ أثناء تحميل المنتجات. يرجى المحاولة مرة أخرى.',
    'home.repair.title': 'خدمة الإصلاح',
    'home.repair.subtitle': 'هل جهازك يحتاج إصلاح؟',
    'home.repair.description': 'نقدم خدمات إصلاح احترافية لجميع أنواع الحواسيب والأجهزة الإلكترونية. فريقنا المتخصص جاهز لمساعدتك.',
    'home.repair.requestBtn': 'طلب إصلاح',
    'home.repair.trackBtn': 'تتبع طلبك',
    
    // Product
    'product.specifications': 'المواصفات',
    'product.addToCart': 'أضف إلى السلة',
    'product.inStock': 'متوفر في المخزون',
    'product.outOfStock': 'غير متوفر',
    'product.loading': 'جاري التحميل...',
    'product.notFound': 'المنتج غير موجود',
    
    // Cart
    'cart.title': 'سلة التسوق',
    'cart.description': 'إدارة منتجات سلة التسوق الخاصة بك',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.browsProducts': 'تصفح المنتجات',
    'cart.remove': 'إزالة',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.total': 'المجموع الكلي',
    'cart.checkout': 'إتمام الطلب',
    'cart.free': 'مجاني',
    'cart.quantity': 'الكمية',
    'cart.error': 'حدث خطأ أثناء تحميل السلة',
    'cart.loginRequired': 'يجب تسجيل الدخول أولاً',
    'cart.loginRequiredDesc': 'قم بتسجيل الدخول لإضافة المنتجات إلى سلة التسوق',
    'cart.addedToCart': 'تمت الإضافة للسلة',
    'cart.addedDescription': 'تم إضافة المنتج إلى سلة التسوق',
    'cart.addError': 'حدث خطأ أثناء إضافة المنتج للسلة',
    'cart.retry': 'إعادة المحاولة',
    'cart.removed': 'تم الحذف',
    'cart.removedDescription': 'تم حذف المنتج من السلة',
    'cart.removeError': 'حدث خطأ أثناء حذف المنتج',
    'cart.quantityUpdateError': 'حدث خطأ أثناء تحديث الكمية',
    
    // Checkout
    'checkout.title': 'إتمام الطلب',
    'checkout.customerInfo': 'معلومات التسليم',
    'checkout.fullName': 'الاسم الكامل',
    'checkout.fullNamePlaceholder': 'أدخل الاسم الكامل',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.phone': 'رقم الهاتف',
    'checkout.address': 'العنوان التفصيلي',
    'checkout.addressPlaceholder': 'الشارع، رقم البيت، أقرب نقطة دالة',
    'checkout.governorate': 'المحافظة',
    'checkout.selectGovernorate': 'اختر المحافظة',
    'checkout.neighborhood': 'المنطقة / الحي',
    'checkout.neighborhoodPlaceholder': 'مثال: الكرادة، المنصور',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.cashOnDelivery': 'الدفع عند الاستلام',
    'checkout.cashOnDeliveryDesc': 'ادفع نقداً عند استلام الطلب',
    'checkout.zainCash': 'زين كاش',
    'checkout.zainCashDesc': 'الدفع عبر محفظة زين كاش الإلكترونية',
    'checkout.fastPay': 'فاست باي',
    'checkout.fastPayDesc': 'الدفع عبر خدمة فاست باي',
    'checkout.onlinePayment': 'الدفع الإلكتروني',
    'checkout.comingSoon': 'قريباً',
    'checkout.confirmOrder': 'تأكيد الطلب',
    'checkout.processing': 'جاري إنشاء الطلب...',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.subtotal': 'المجموع الفرعي',
    'checkout.shipping': 'التوصيل',
    'checkout.freeShipping': 'مجاني',
    'checkout.freeShippingThreshold': 'اطلب بقيمة {amount} د.ع أو أكثر للحصول على توصيل مجاني',
    'checkout.orderSuccess': 'تم إنشاء الطلب بنجاح!',
    'checkout.orderError': 'فشل إنشاء الطلب. يرجى المحاولة مرة أخرى.',
    'checkout.loading': 'جاري تحميل السلة...',
    'checkout.addProductsFirst': 'يرجى إضافة منتجات قبل المتابعة إلى الدفع',
    'checkout.backToStore': 'العودة للمتجر',
    
    // Login
    'login.title': 'تسجيل الدخول',
    'login.description': 'سجل دخولك للمتابعة في الشراء',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.register': 'إنشاء حساب',
    'login.loggingIn': 'جاري تسجيل الدخول...',
    'login.success.title': 'تم تسجيل الدخول بنجاح',
    'login.success.description': 'مرحباً بك مرة أخرى',
    'login.error.title': 'خطأ في تسجيل الدخول',
    'login.error.description': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'login.backToHome': 'العودة للرئيسية',
    
    // Register
    'register.title': 'إنشاء حساب جديد',
    'register.description': 'أنشئ حسابك للبدء في التسوق',
    'register.name': 'الاسم الكامل',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.phonePlaceholder': '٠٧٩٠٠٠٠٠٠٠٠',
    'register.password': 'كلمة المرور',
    'register.passwordHint': 'يجب أن تكون 6 أحرف على الأقل',
    'register.submit': 'إنشاء حساب',
    'register.hasAccount': 'لديك حساب بالفعل؟',
    'register.login': 'تسجيل الدخول',
    'register.registering': 'جاري إنشاء الحساب...',
    'register.success.title': 'تم إنشاء الحساب بنجاح',
    'register.success.description': 'مرحباً بك في العين لتجارة الحاسبات',
    'register.error.title': 'خطأ في إنشاء الحساب',
    'register.error.description': 'حدث خطأ، يرجى المحاولة مرة أخرى',
    'register.backToHome': 'العودة للرئيسية',
    
    // Admin
    'admin.login.title': 'تسجيل دخول المسؤول',
    'admin.login.password': 'كلمة المرور',
    'admin.login.passwordPlaceholder': 'أدخل كلمة المرور',
    'admin.login.submit': 'تسجيل الدخول',
    'admin.dashboard.title': 'لوحة التحكم',
    'admin.dashboard.ordersTitle': 'إدارة الطلبات',
    'admin.dashboard.ordersCount': 'عدد الطلبات',
    'admin.dashboard.noOrders': 'لا توجد طلبات حالياً',
    'admin.dashboard.orders': 'الطلبات',
    'admin.dashboard.orderNumber': 'رقم الطلب',
    'admin.dashboard.customer': 'العميل',
    'admin.dashboard.email': 'البريد الإلكتروني',
    'admin.dashboard.phone': 'رقم الهاتف',
    'admin.dashboard.city': 'المدينة',
    'admin.dashboard.itemsCount': 'عدد العناصر',
    'admin.dashboard.item': 'عنصر',
    'admin.dashboard.total': 'المجموع',
    'admin.dashboard.status': 'الحالة',
    'admin.dashboard.date': 'التاريخ',
    'admin.dashboard.update': 'تحديث',
    'admin.dashboard.updating': 'جاري التحديث...',
    'admin.dashboard.logout': 'تسجيل الخروج',
    'admin.dashboard.pending': 'قيد الانتظار',
    'admin.dashboard.processing': 'قيد المعالجة',
    'admin.dashboard.shipped': 'تم الشحن',
    'admin.dashboard.delivered': 'تم التسليم',
    'admin.dashboard.cancelled': 'ملغاة',
    'admin.dashboard.updateSuccess': 'تم التحديث بنجاح',
    'admin.dashboard.updateSuccessDesc': 'تم تحديث حالة الطلب',
    'admin.dashboard.updateError': 'خطأ',
    'admin.dashboard.updateErrorDesc': 'فشل تحديث الطلب',
    'admin.dashboard.logoutSuccess': 'تسجيل الخروج',
    'admin.dashboard.logoutSuccessDesc': 'تم تسجيل خروجك بنجاح',
    
    // Admin Products
    'admin.products.title': 'إدارة المنتجات',
    'admin.products.addNew': 'إضافة منتج جديد',
    'admin.products.edit': 'تعديل',
    'admin.products.delete': 'حذف',
    'admin.products.confirmDelete': 'هل أنت متأكد من حذف هذا المنتج؟',
    'admin.products.nameAr': 'الاسم بالعربي',
    'admin.products.nameEn': 'الاسم بالإنجليزي',
    'admin.products.descAr': 'الوصف بالعربي',
    'admin.products.descEn': 'الوصف بالإنجليزي',
    'admin.products.price': 'السعر',
    'admin.products.oldPrice': 'السعر القديم',
    'admin.products.category': 'الفئة',
    'admin.products.image': 'رابط الصورة',
    'admin.products.badge': 'الشارة',
    'admin.products.inStock': 'متوفر',
    'admin.products.specs': 'المواصفات (سطر لكل مواصفة)',
    'admin.products.save': 'حفظ',
    'admin.products.cancel': 'إلغاء',
    'admin.products.creating': 'جاري الإنشاء...',
    'admin.products.updating': 'جاري التحديث...',
    'admin.products.deleting': 'جاري الحذف...',
    'admin.products.actions': 'الإجراءات',
    'admin.products.manageProducts': 'إدارة المنتجات',
    'admin.products.imagePlaceholder': 'product_image.png',
    
    // Admin Settings
    'admin.settings.title': 'إعدادات المتجر',
    'admin.settings.storeInfo': 'معلومات المتجر',
    'admin.settings.storeInfoDesc': 'قم بتحديث اسم المتجر ووصفه',
    'admin.settings.contactInfo': 'معلومات الاتصال',
    'admin.settings.contactInfoDesc': 'قم بتحديث البريد الإلكتروني والهاتف والموقع',
    'admin.settings.socialMedia': 'وسائل التواصل الاجتماعي',
    'admin.settings.socialMediaDesc': 'قم بإضافة روابط حساباتك على وسائل التواصل',
    'admin.settings.storeNameAr': 'اسم المتجر بالعربية',
    'admin.settings.storeNameEn': 'اسم المتجر بالإنجليزية',
    'admin.settings.descriptionAr': 'الوصف بالعربية',
    'admin.settings.descriptionEn': 'الوصف بالإنجليزية',
    'admin.settings.email': 'البريد الإلكتروني',
    'admin.settings.phone': 'رقم الهاتف',
    'admin.settings.phoneAr': 'رقم الهاتف بالعربية',
    'admin.settings.addressAr': 'العنوان بالعربية',
    'admin.settings.addressEn': 'العنوان بالإنجليزية',
    'admin.settings.hoursAr': 'ساعات العمل بالعربية',
    'admin.settings.hoursEn': 'ساعات العمل بالإنجليزية',
    'admin.settings.facebookUrl': 'رابط فيسبوك',
    'admin.settings.twitterUrl': 'رابط تويتر',
    'admin.settings.instagramUrl': 'رابط انستجرام',
    'admin.settings.whatsappNumber': 'رقم واتساب',
    'admin.settings.whatsappNumberHint': 'رقم الهاتف بالصيغة الدولية (مثال: +964 770 123 4567)',
    'admin.settings.save': 'حفظ الإعدادات',
    'admin.settings.successTitle': 'تم الحفظ',
    'admin.settings.successMessage': 'تم حفظ إعدادات المتجر بنجاح',
    'admin.settings.errorMessage': 'فشل حفظ الإعدادات',
    'admin.settings.manageSettings': 'إعدادات المتجر',
    'admin.settings.validation.storeNameArRequired': 'اسم المتجر بالعربية مطلوب',
    'admin.settings.validation.storeNameEnRequired': 'اسم المتجر بالإنجليزية مطلوب',
    'admin.settings.validation.descriptionArRequired': 'الوصف بالعربية مطلوب',
    'admin.settings.validation.descriptionEnRequired': 'الوصف بالإنجليزية مطلوب',
    'admin.settings.validation.emailInvalid': 'البريد الإلكتروني غير صحيح',
    'admin.settings.validation.phoneRequired': 'رقم الهاتف مطلوب',
    'admin.settings.validation.phoneArRequired': 'رقم الهاتف بالعربية مطلوب',
    'admin.settings.validation.addressArRequired': 'العنوان بالعربية مطلوب',
    'admin.settings.validation.addressEnRequired': 'العنوان بالإنجليزية مطلوب',
    'admin.settings.validation.hoursArRequired': 'ساعات العمل بالعربية مطلوبة',
    'admin.settings.validation.hoursEnRequired': 'ساعات العمل بالإنجليزية مطلوبة',
    
    // Admin Settings Tabs
    'admin.settings.tabs.store': 'المتجر',
    'admin.settings.tabs.theme': 'المظهر',
    'admin.settings.tabs.seo': 'SEO',
    'admin.settings.tabs.homepage': 'الصفحة الرئيسية',
    'admin.settings.tabs.footer': 'التذييل',
    'admin.settings.tabs.shipping': 'الشحن والدفع',
    
    // Theme Settings
    'admin.settings.theme.branding': 'العلامة التجارية',
    'admin.settings.theme.brandingDesc': 'قم بتحميل شعار المتجر والأيقونة',
    'admin.settings.theme.logoUrl': 'رابط الشعار',
    'admin.settings.theme.logoUrlHint': 'رابط صورة شعار المتجر',
    'admin.settings.theme.faviconUrl': 'رابط الأيقونة',
    'admin.settings.theme.faviconUrlHint': 'رابط أيقونة المتجر (favicon)',
    'admin.settings.theme.colors': 'الألوان',
    'admin.settings.theme.colorsDesc': 'اختر ألوان المتجر الأساسية',
    'admin.settings.theme.primaryColor': 'اللون الأساسي',
    'admin.settings.theme.accentColor': 'اللون الثانوي',
    'admin.settings.theme.currency': 'العملة',
    'admin.settings.theme.currencyDesc': 'إعدادات عرض العملة',
    'admin.settings.theme.currencySymbolAr': 'رمز العملة بالعربية',
    'admin.settings.theme.currencySymbolEn': 'رمز العملة بالإنجليزية',
    
    // SEO Settings
    'admin.settings.seo.metaTitle': 'عنوان الصفحة',
    'admin.settings.seo.metaTitleDesc': 'العنوان الذي يظهر في نتائج البحث',
    'admin.settings.seo.metaTitleAr': 'عنوان الصفحة بالعربية',
    'admin.settings.seo.metaTitleEn': 'عنوان الصفحة بالإنجليزية',
    'admin.settings.seo.metaDescription': 'وصف الصفحة',
    'admin.settings.seo.metaDescriptionDesc': 'الوصف الذي يظهر في نتائج البحث',
    'admin.settings.seo.metaDescriptionAr': 'وصف الصفحة بالعربية',
    'admin.settings.seo.metaDescriptionEn': 'وصف الصفحة بالإنجليزية',
    'admin.settings.seo.keywords': 'الكلمات المفتاحية',
    'admin.settings.seo.keywordsDesc': 'الكلمات المفتاحية لمحركات البحث',
    'admin.settings.seo.keywordsAr': 'الكلمات المفتاحية بالعربية',
    'admin.settings.seo.keywordsEn': 'الكلمات المفتاحية بالإنجليزية',
    'admin.settings.seo.keywordsPlaceholder': 'كلمة1، كلمة2، كلمة3',
    
    // Homepage Settings
    'admin.settings.homepage.hero': 'البانر الرئيسي',
    'admin.settings.homepage.heroDesc': 'إعدادات البانر في الصفحة الرئيسية',
    'admin.settings.homepage.showHeroBanner': 'إظهار البانر الرئيسي',
    'admin.settings.homepage.heroTitleAr': 'عنوان البانر بالعربية',
    'admin.settings.homepage.heroTitleEn': 'عنوان البانر بالإنجليزية',
    'admin.settings.homepage.heroSubtitleAr': 'العنوان الفرعي بالعربية',
    'admin.settings.homepage.heroSubtitleEn': 'العنوان الفرعي بالإنجليزية',
    'admin.settings.homepage.heroImageUrl': 'رابط صورة البانر',
    'admin.settings.homepage.heroImageHint': 'يفضل صورة بحجم 1920x600 بكسل',
    'admin.settings.homepage.sections': 'أقسام الصفحة الرئيسية',
    'admin.settings.homepage.sectionsDesc': 'تحكم في الأقسام المعروضة',
    'admin.settings.homepage.showCategories': 'إظهار قسم الفئات',
    'admin.settings.homepage.showFeaturedProducts': 'إظهار المنتجات المميزة',
    'admin.settings.homepage.featuredProductsCount': 'عدد المنتجات المميزة',
    
    // Footer Settings
    'admin.settings.footer.about': 'نص عن المتجر',
    'admin.settings.footer.aboutDesc': 'النص الذي يظهر في تذييل الصفحة',
    'admin.settings.footer.aboutTextAr': 'نص عن المتجر بالعربية',
    'admin.settings.footer.aboutTextEn': 'نص عن المتجر بالإنجليزية',
    'admin.settings.footer.copyright': 'حقوق النشر',
    'admin.settings.footer.copyrightDesc': 'نص حقوق النشر في التذييل',
    'admin.settings.footer.copyrightTextAr': 'نص حقوق النشر بالعربية',
    'admin.settings.footer.copyrightTextEn': 'نص حقوق النشر بالإنجليزية',
    
    // Shipping Settings
    'admin.settings.shipping.title': 'إعدادات الشحن',
    'admin.settings.shipping.description': 'تحكم في تكاليف الشحن والتوصيل',
    'admin.settings.shipping.cost': 'تكلفة الشحن',
    'admin.settings.shipping.costHint': 'تكلفة الشحن بالدينار العراقي',
    'admin.settings.shipping.freeThreshold': 'حد الشحن المجاني',
    'admin.settings.shipping.freeThresholdHint': 'الحد الأدنى للطلب للحصول على شحن مجاني',
    'admin.settings.shipping.enableFreeShipping': 'تفعيل الشحن المجاني',
    
    // Payment Settings
    'admin.settings.payment.title': 'طرق الدفع',
    'admin.settings.payment.description': 'تحكم في طرق الدفع المتاحة',
    'admin.settings.payment.cashOnDelivery': 'الدفع عند الاستلام',
    'admin.settings.payment.electronicPayment': 'الدفع الإلكتروني',
    
    // Categories
    'categories.laptops': 'أجهزة لابتوب',
    'categories.desktops': 'أجهزة مكتبية',
    'categories.monitors': 'شاشات',
    'categories.accessories': 'إكسسوارات',
    
    // Footer
    'footer.about': 'عن',
    'footer.defaultStoreName': 'العين لتجارة الحاسبات',
    'footer.defaultDescription': 'متجرك الموثوق لأحدث الحواسيب والملحقات بأفضل الأسعار وأعلى جودة',
    'footer.email': 'البريد الإلكتروني:',
    'footer.phone': 'الهاتف:',
    'footer.hours': 'ساعات العمل:',
    'footer.defaultEmail': 'info@alain-computers.com',
    'footer.defaultPhone': '٩٢٠٠٠١٢٣٤',
    'footer.defaultHours': 'السبت - الخميس ٩ص - ٩م',
    'footer.quickLinks': 'روابط سريعة',
    'footer.aboutUs': 'من نحن',
    'footer.contact': 'اتصل بنا',
    'footer.branches': 'فروعنا',
    'footer.careers': 'الوظائف',
    'footer.customerService': 'خدمة العملاء',
    'footer.shipping': 'سياسة الشحن',
    'footer.returns': 'الاستبدال والاسترجاع',
    'footer.warranty': 'الضمان',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.newsletter': 'اشترك في النشرة الإخبارية',
    'footer.newsletterDesc': 'احصل على آخر العروض والأخبار',
    'footer.newsletterPlaceholder': 'بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
    'footer.followUs': 'تابعنا',
    'footer.whatsapp': 'تواصل معنا عبر واتساب',
    'footer.copyright': '© ٢٠٢٥ العين لتجارة الحاسبات. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'الشروط والأحكام',
    
    // Repair Tracking
    'repair.request.title': 'طلب إصلاح',
    'repair.request.description': 'أرسل جهازك للإصلاح',
    'repair.request.customerInfo': 'معلومات العميل',
    'repair.request.deviceInfo': 'معلومات الجهاز',
    'repair.request.customerName': 'الاسم الكامل',
    'repair.request.customerPhone': 'رقم الهاتف',
    'repair.request.customerEmail': 'البريد الإلكتروني (اختياري)',
    'repair.request.deviceType': 'نوع الجهاز',
    'repair.request.deviceBrand': 'العلامة التجارية',
    'repair.request.deviceModel': 'الموديل',
    'repair.request.issueDescription': 'وصف المشكلة',
    'repair.request.issueDescriptionPlaceholder': 'صف المشكلة بالتفصيل...',
    'repair.request.submit': 'إرسال طلب الإصلاح',
    'repair.request.submitting': 'جاري الإرسال...',
    'repair.request.successTitle': 'تم إرسال الطلب',
    'repair.request.successMessage': 'رقم التذكرة: {ticketNumber}',
    'repair.request.successNote': 'احفظ رقم التذكرة لمتابعة حالة الإصلاح',
    'repair.request.errorTitle': 'فشل إرسال الطلب',
    'repair.request.errorMessage': 'حدث خطأ، يرجى المحاولة مرة أخرى',
    
    'repair.lookup.title': 'تتبع الإصلاح',
    'repair.lookup.description': 'تحقق من حالة طلب الإصلاح',
    'repair.lookup.ticketNumber': 'رقم التذكرة',
    'repair.lookup.ticketNumberPlaceholder': 'REP-٠٠٠٠١',
    'repair.lookup.search': 'بحث',
    'repair.lookup.searching': 'جاري البحث...',
    'repair.lookup.notFound': 'لم يتم العثور على التذكرة',
    'repair.lookup.errorMessage': 'حدث خطأ أثناء البحث',
    
    'repair.ticket.details': 'تفاصيل التذكرة',
    'repair.ticket.ticketNumber': 'رقم التذكرة',
    'repair.ticket.status': 'الحالة',
    'repair.ticket.priority': 'الأولوية',
    'repair.ticket.createdAt': 'تاريخ الإنشاء',
    'repair.ticket.updatedAt': 'آخر تحديث',
    'repair.ticket.estimatedCompletion': 'التاريخ المتوقع للإنجاز',
    'repair.ticket.costEstimate': 'التكلفة المقدرة',
    'repair.ticket.finalCost': 'التكلفة النهائية',
    'repair.ticket.technicianNotes': 'ملاحظات الفني',
    'repair.ticket.customerName': 'اسم العميل',
    'repair.ticket.customerPhone': 'هاتف العميل',
    'repair.ticket.customerEmail': 'بريد العميل',
    'repair.ticket.deviceType': 'نوع الجهاز',
    'repair.ticket.deviceBrand': 'العلامة التجارية',
    'repair.ticket.deviceModel': 'الموديل',
    'repair.ticket.issueDescription': 'وصف المشكلة',
    
    'repair.status.pending': 'قيد الانتظار',
    'repair.status.in-progress': 'قيد الإصلاح',
    'repair.status.waiting-parts': 'بانتظار القطع',
    'repair.status.completed': 'مكتمل',
    'repair.status.delivered': 'تم التسليم',
    
    'repair.priority.low': 'منخفضة',
    'repair.priority.normal': 'عادية',
    'repair.priority.high': 'عالية',
    'repair.priority.urgent': 'عاجلة',
    
    'repair.deviceType.laptop': 'لابتوب',
    'repair.deviceType.desktop': 'جهاز مكتبي',
    'repair.deviceType.monitor': 'شاشة',
    'repair.deviceType.printer': 'طابعة',
    'repair.deviceType.other': 'أخرى',
    
    'repair.technician.login.title': 'دخول الفني',
    'repair.technician.login.description': 'أدخل كلمة المرور للوصول إلى لوحة الفني',
    'repair.technician.login.password': 'كلمة المرور',
    'repair.technician.login.passwordPlaceholder': 'أدخل كلمة المرور',
    'repair.technician.login.submit': 'تسجيل الدخول',
    'repair.technician.login.successTitle': 'تم تسجيل الدخول',
    'repair.technician.login.successDescription': 'مرحباً بك مرة أخرى',
    'repair.technician.login.errorTitle': 'خطأ',
    'repair.technician.login.errorDescription': 'كلمة المرور غير صحيحة',
    'repair.technician.dashboard.title': 'لوحة الفني',
    'repair.technician.dashboard.allTickets': 'جميع التذاكر',
    'repair.technician.dashboard.newTicket': 'تذكرة جديدة',
    'repair.technician.dashboard.filterStatus': 'تصفية حسب الحالة',
    'repair.technician.dashboard.filterPriority': 'تصفية حسب الأولوية',
    'repair.technician.dashboard.searchPhone': 'البحث برقم الهاتف...',
    'repair.technician.dashboard.noTickets': 'لا توجد تذاكر',
    
    'repair.edit.title': 'تحديث التذكرة',
    'repair.edit.updateStatus': 'تحديث الحالة',
    'repair.edit.updatePriority': 'تحديث الأولوية',
    'repair.edit.addNotes': 'إضافة ملاحظات',
    'repair.edit.setEstimatedCompletion': 'تحديد تاريخ الإنجاز المتوقع',
    'repair.edit.setCostEstimate': 'تحديد التكلفة المقدرة',
    'repair.edit.setFinalCost': 'تحديد التكلفة النهائية',
    'repair.edit.save': 'حفظ التغييرات',
    'repair.edit.saving': 'جاري الحفظ...',
    'repair.edit.successTitle': 'تم التحديث',
    'repair.edit.successMessage': 'تم تحديث التذكرة بنجاح',
    'repair.edit.errorMessage': 'فشل تحديث التذكرة',
    
    // Common
    'common.currency': 'د.ع',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.ok': 'حسناً',
    'common.back': 'رجوع',
  },
  en: {
    // Header
    'header.title': 'Al-Ain Computer Trading',
    'header.home': 'Home',
    'header.categories': 'Categories',
    'header.cart': 'Cart',
    'header.login': 'Login',
    'header.profile': 'Profile',
    'header.logout': 'Logout',
    'header.searchPlaceholder': 'Search for products...',
    'header.searchTitle': 'Search',
    'header.searchDescription': 'Search for computers and accessories',
    
    // Categories
    'category.all': 'All Products',
    'category.laptops': 'Laptops',
    'category.desktops': 'Desktops',
    'category.monitors': 'Monitors',
    'category.accessories': 'Accessories',
    
    // Home page
    'home.hero.title': 'Best Computers & Accessories',
    'home.hero.subtitle': 'Discover the latest technology at the best prices',
    'home.hero.cta': 'Shop Now',
    'home.categories.title': 'Browse by Category',
    'home.featured.title': 'Featured Products',
    'home.hero.imageAlt': 'Store promotional banner',
    'home.searchResultsFor': 'Search results for: {query}',
    'home.showAll': 'Show All',
    'home.noProducts': 'No products available',
    'home.noSearchResults': 'No products match your search',
    'home.loadError': 'An error occurred while loading products. Please try again.',
    'home.repair.title': 'Repair Service',
    'home.repair.subtitle': 'Does your device need repair?',
    'home.repair.description': 'We offer professional repair services for all types of computers and electronic devices. Our specialized team is ready to help you.',
    'home.repair.requestBtn': 'Request Repair',
    'home.repair.trackBtn': 'Track Your Request',
    
    // Product
    'product.specifications': 'Specifications',
    'product.addToCart': 'Add to Cart',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.loading': 'Loading...',
    'product.notFound': 'Product not found',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.description': 'Manage your shopping cart items',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.browsProducts': 'Browse Products',
    'cart.remove': 'Remove',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.free': 'Free',
    'cart.quantity': 'Quantity',
    'cart.error': 'An error occurred while loading the cart',
    'cart.loginRequired': 'Login Required',
    'cart.loginRequiredDesc': 'Please login to add products to your shopping cart',
    'cart.addedToCart': 'Added to Cart',
    'cart.addedDescription': 'Product has been added to your cart',
    'cart.addError': 'An error occurred while adding the product',
    'cart.retry': 'Retry',
    'cart.removed': 'Removed',
    'cart.removedDescription': 'Product removed from cart',
    'cart.removeError': 'An error occurred while removing the product',
    'cart.quantityUpdateError': 'An error occurred while updating quantity',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.customerInfo': 'Delivery Information',
    'checkout.fullName': 'Full Name',
    'checkout.fullNamePlaceholder': 'Enter your full name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Detailed Address',
    'checkout.addressPlaceholder': 'Street, house number, nearest landmark',
    'checkout.governorate': 'Governorate',
    'checkout.selectGovernorate': 'Select governorate',
    'checkout.neighborhood': 'Neighborhood / Area',
    'checkout.neighborhoodPlaceholder': 'e.g., Karrada, Mansour',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.cashOnDeliveryDesc': 'Pay in cash when you receive your order',
    'checkout.zainCash': 'ZainCash',
    'checkout.zainCashDesc': 'Pay via ZainCash mobile wallet',
    'checkout.fastPay': 'FastPay',
    'checkout.fastPayDesc': 'Pay via FastPay service',
    'checkout.onlinePayment': 'Online Payment',
    'checkout.comingSoon': 'Coming Soon',
    'checkout.confirmOrder': 'Confirm Order',
    'checkout.processing': 'Processing order...',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Delivery',
    'checkout.freeShipping': 'Free',
    'checkout.freeShippingThreshold': 'Order {amount} IQD or more for free delivery',
    'checkout.orderSuccess': 'Order placed successfully!',
    'checkout.orderError': 'Failed to place order. Please try again.',
    'checkout.loading': 'Loading cart...',
    'checkout.addProductsFirst': 'Please add products before proceeding to checkout',
    'checkout.backToStore': 'Back to Store',
    
    // Login
    'login.title': 'Login',
    'login.description': 'Login to continue shopping',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Create Account',
    'login.loggingIn': 'Logging in...',
    'login.success.title': 'Login successful',
    'login.success.description': 'Welcome back',
    'login.error.title': 'Login error',
    'login.error.description': 'Invalid email or password',
    'login.backToHome': 'Back to Home',
    
    // Register
    'register.title': 'Create New Account',
    'register.description': 'Create your account to start shopping',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.passwordHint': 'Must be at least 6 characters',
    'register.submit': 'Create Account',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.registering': 'Creating account...',
    'register.success.title': 'Account created successfully',
    'register.success.description': 'Welcome to Al-Ain Computer Trading',
    'register.error.title': 'Error creating account',
    'register.error.description': 'An error occurred, please try again',
    'register.backToHome': 'Back to Home',
    
    // Admin
    'admin.login.title': 'Admin Login',
    'admin.login.password': 'Password',
    'admin.login.submit': 'Login',
    'admin.dashboard.title': 'Dashboard',
    'admin.dashboard.ordersTitle': 'Order Management',
    'admin.dashboard.ordersCount': 'Order Count',
    'admin.dashboard.noOrders': 'No orders currently',
    'admin.dashboard.orders': 'Orders',
    'admin.dashboard.orderNumber': 'Order #',
    'admin.dashboard.customer': 'Customer',
    'admin.dashboard.email': 'Email',
    'admin.dashboard.phone': 'Phone',
    'admin.dashboard.city': 'City',
    'admin.dashboard.itemsCount': 'Items Count',
    'admin.dashboard.item': 'item',
    'admin.dashboard.total': 'Total',
    'admin.dashboard.status': 'Status',
    'admin.dashboard.date': 'Date',
    'admin.dashboard.update': 'Update',
    'admin.dashboard.updating': 'Updating...',
    'admin.dashboard.logout': 'Logout',
    'admin.dashboard.pending': 'Pending',
    'admin.dashboard.processing': 'Processing',
    'admin.dashboard.shipped': 'Shipped',
    'admin.dashboard.delivered': 'Delivered',
    'admin.dashboard.cancelled': 'Cancelled',
    'admin.dashboard.updateSuccess': 'Update Successful',
    'admin.dashboard.updateSuccessDesc': 'Order status updated',
    'admin.dashboard.updateError': 'Error',
    'admin.dashboard.updateErrorDesc': 'Failed to update order',
    'admin.dashboard.logoutSuccess': 'Logged Out',
    'admin.dashboard.logoutSuccessDesc': 'You have been logged out successfully',
    
    // Admin Products
    'admin.products.title': 'Manage Products',
    'admin.products.addNew': 'Add New Product',
    'admin.products.edit': 'Edit',
    'admin.products.delete': 'Delete',
    'admin.products.confirmDelete': 'Are you sure you want to delete this product?',
    'admin.products.nameAr': 'Arabic Name',
    'admin.products.nameEn': 'English Name',
    'admin.products.descAr': 'Arabic Description',
    'admin.products.descEn': 'English Description',
    'admin.products.price': 'Price',
    'admin.products.oldPrice': 'Old Price',
    'admin.products.category': 'Category',
    'admin.products.image': 'Image URL',
    'admin.products.badge': 'Badge',
    'admin.products.inStock': 'In Stock',
    'admin.products.specs': 'Specifications (one per line)',
    'admin.products.save': 'Save',
    'admin.products.cancel': 'Cancel',
    'admin.products.creating': 'Creating...',
    'admin.products.updating': 'Updating...',
    'admin.products.deleting': 'Deleting...',
    'admin.products.actions': 'Actions',
    'admin.products.manageProducts': 'Manage Products',
    'admin.products.imagePlaceholder': 'product_image.png',
    
    // Admin Settings
    'admin.settings.title': 'Store Settings',
    'admin.settings.storeInfo': 'Store Information',
    'admin.settings.storeInfoDesc': 'Update your store name and description',
    'admin.settings.contactInfo': 'Contact Information',
    'admin.settings.contactInfoDesc': 'Update email, phone, and location',
    'admin.settings.socialMedia': 'Social Media',
    'admin.settings.socialMediaDesc': 'Add your social media profile links',
    'admin.settings.storeNameAr': 'Store Name (Arabic)',
    'admin.settings.storeNameEn': 'Store Name (English)',
    'admin.settings.descriptionAr': 'Description (Arabic)',
    'admin.settings.descriptionEn': 'Description (English)',
    'admin.settings.email': 'Email Address',
    'admin.settings.phone': 'Phone Number',
    'admin.settings.phoneAr': 'Phone Number (Arabic)',
    'admin.settings.addressAr': 'Address (Arabic)',
    'admin.settings.addressEn': 'Address (English)',
    'admin.settings.hoursAr': 'Working Hours (Arabic)',
    'admin.settings.hoursEn': 'Working Hours (English)',
    'admin.settings.facebookUrl': 'Facebook URL',
    'admin.settings.twitterUrl': 'Twitter URL',
    'admin.settings.instagramUrl': 'Instagram URL',
    'admin.settings.whatsappNumber': 'WhatsApp Number',
    'admin.settings.whatsappNumberHint': 'Phone number in international format (e.g., +964 770 123 4567)',
    'admin.settings.save': 'Save Settings',
    'admin.settings.successTitle': 'Saved',
    'admin.settings.successMessage': 'Store settings saved successfully',
    'admin.settings.errorMessage': 'Failed to save settings',
    'admin.settings.manageSettings': 'Store Settings',
    'admin.settings.validation.storeNameArRequired': 'Store name in Arabic is required',
    'admin.settings.validation.storeNameEnRequired': 'Store name in English is required',
    'admin.settings.validation.descriptionArRequired': 'Description in Arabic is required',
    'admin.settings.validation.descriptionEnRequired': 'Description in English is required',
    'admin.settings.validation.emailInvalid': 'Invalid email address',
    'admin.settings.validation.phoneRequired': 'Phone number is required',
    'admin.settings.validation.phoneArRequired': 'Phone number in Arabic is required',
    'admin.settings.validation.addressArRequired': 'Address in Arabic is required',
    'admin.settings.validation.addressEnRequired': 'Address in English is required',
    'admin.settings.validation.hoursArRequired': 'Working hours in Arabic are required',
    'admin.settings.validation.hoursEnRequired': 'Working hours in English are required',
    
    // Admin Settings Tabs
    'admin.settings.tabs.store': 'Store',
    'admin.settings.tabs.theme': 'Theme',
    'admin.settings.tabs.seo': 'SEO',
    'admin.settings.tabs.homepage': 'Homepage',
    'admin.settings.tabs.footer': 'Footer',
    'admin.settings.tabs.shipping': 'Shipping & Payment',
    
    // Theme Settings
    'admin.settings.theme.branding': 'Branding',
    'admin.settings.theme.brandingDesc': 'Upload your store logo and favicon',
    'admin.settings.theme.logoUrl': 'Logo URL',
    'admin.settings.theme.logoUrlHint': 'URL to your store logo image',
    'admin.settings.theme.faviconUrl': 'Favicon URL',
    'admin.settings.theme.faviconUrlHint': 'URL to your store favicon',
    'admin.settings.theme.colors': 'Colors',
    'admin.settings.theme.colorsDesc': 'Choose your store primary colors',
    'admin.settings.theme.primaryColor': 'Primary Color',
    'admin.settings.theme.accentColor': 'Accent Color',
    'admin.settings.theme.currency': 'Currency',
    'admin.settings.theme.currencyDesc': 'Currency display settings',
    'admin.settings.theme.currencySymbolAr': 'Currency Symbol (Arabic)',
    'admin.settings.theme.currencySymbolEn': 'Currency Symbol (English)',
    
    // SEO Settings
    'admin.settings.seo.metaTitle': 'Page Title',
    'admin.settings.seo.metaTitleDesc': 'Title that appears in search results',
    'admin.settings.seo.metaTitleAr': 'Page Title (Arabic)',
    'admin.settings.seo.metaTitleEn': 'Page Title (English)',
    'admin.settings.seo.metaDescription': 'Page Description',
    'admin.settings.seo.metaDescriptionDesc': 'Description that appears in search results',
    'admin.settings.seo.metaDescriptionAr': 'Page Description (Arabic)',
    'admin.settings.seo.metaDescriptionEn': 'Page Description (English)',
    'admin.settings.seo.keywords': 'Keywords',
    'admin.settings.seo.keywordsDesc': 'Keywords for search engines',
    'admin.settings.seo.keywordsAr': 'Keywords (Arabic)',
    'admin.settings.seo.keywordsEn': 'Keywords (English)',
    'admin.settings.seo.keywordsPlaceholder': 'keyword1, keyword2, keyword3',
    
    // Homepage Settings
    'admin.settings.homepage.hero': 'Hero Banner',
    'admin.settings.homepage.heroDesc': 'Homepage hero banner settings',
    'admin.settings.homepage.showHeroBanner': 'Show Hero Banner',
    'admin.settings.homepage.heroTitleAr': 'Hero Title (Arabic)',
    'admin.settings.homepage.heroTitleEn': 'Hero Title (English)',
    'admin.settings.homepage.heroSubtitleAr': 'Hero Subtitle (Arabic)',
    'admin.settings.homepage.heroSubtitleEn': 'Hero Subtitle (English)',
    'admin.settings.homepage.heroImageUrl': 'Hero Image URL',
    'admin.settings.homepage.heroImageHint': 'Recommended size: 1920x600 pixels',
    'admin.settings.homepage.sections': 'Homepage Sections',
    'admin.settings.homepage.sectionsDesc': 'Control which sections are displayed',
    'admin.settings.homepage.showCategories': 'Show Categories Section',
    'admin.settings.homepage.showFeaturedProducts': 'Show Featured Products',
    'admin.settings.homepage.featuredProductsCount': 'Number of Featured Products',
    
    // Footer Settings
    'admin.settings.footer.about': 'About Text',
    'admin.settings.footer.aboutDesc': 'Text displayed in the footer',
    'admin.settings.footer.aboutTextAr': 'About Text (Arabic)',
    'admin.settings.footer.aboutTextEn': 'About Text (English)',
    'admin.settings.footer.copyright': 'Copyright',
    'admin.settings.footer.copyrightDesc': 'Copyright text in footer',
    'admin.settings.footer.copyrightTextAr': 'Copyright Text (Arabic)',
    'admin.settings.footer.copyrightTextEn': 'Copyright Text (English)',
    
    // Shipping Settings
    'admin.settings.shipping.title': 'Shipping Settings',
    'admin.settings.shipping.description': 'Manage shipping and delivery costs',
    'admin.settings.shipping.cost': 'Shipping Cost',
    'admin.settings.shipping.costHint': 'Shipping cost in Iraqi Dinar',
    'admin.settings.shipping.freeThreshold': 'Free Shipping Threshold',
    'admin.settings.shipping.freeThresholdHint': 'Minimum order amount for free shipping',
    'admin.settings.shipping.enableFreeShipping': 'Enable Free Shipping',
    
    // Payment Settings
    'admin.settings.payment.title': 'Payment Methods',
    'admin.settings.payment.description': 'Manage available payment methods',
    'admin.settings.payment.cashOnDelivery': 'Cash on Delivery',
    'admin.settings.payment.electronicPayment': 'Electronic Payment',
    
    // Categories
    'categories.laptops': 'Laptops',
    'categories.desktops': 'Desktops',
    'categories.monitors': 'Monitors',
    'categories.accessories': 'Accessories',
    
    // Footer
    'footer.about': 'About',
    'footer.defaultStoreName': 'Al-Ain Computer Trading',
    'footer.defaultDescription': 'Your trusted store for the latest computers and accessories at the best prices and highest quality',
    'footer.email': 'Email:',
    'footer.phone': 'Phone:',
    'footer.hours': 'Working Hours:',
    'footer.defaultEmail': 'info@alain-computers.com',
    'footer.defaultPhone': '920001234',
    'footer.defaultHours': 'Saturday - Thursday 9am - 9pm',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact Us',
    'footer.branches': 'Our Branches',
    'footer.careers': 'Careers',
    'footer.customerService': 'Customer Service',
    'footer.shipping': 'Shipping Policy',
    'footer.returns': 'Returns & Exchanges',
    'footer.warranty': 'Warranty',
    'footer.faq': 'FAQ',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.newsletterDesc': 'Get the latest offers and news',
    'footer.newsletterPlaceholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.followUs': 'Follow Us',
    'footer.whatsapp': 'Contact us on WhatsApp',
    'footer.copyright': '© 2025 Al-Ain Computer Trading. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    
    // Repair Tracking
    'repair.request.title': 'Repair Request',
    'repair.request.description': 'Submit your device for repair',
    'repair.request.customerInfo': 'Customer Information',
    'repair.request.deviceInfo': 'Device Information',
    'repair.request.customerName': 'Full Name',
    'repair.request.customerPhone': 'Phone Number',
    'repair.request.customerEmail': 'Email (Optional)',
    'repair.request.deviceType': 'Device Type',
    'repair.request.deviceBrand': 'Brand',
    'repair.request.deviceModel': 'Model',
    'repair.request.issueDescription': 'Issue Description',
    'repair.request.issueDescriptionPlaceholder': 'Describe the issue in detail...',
    'repair.request.submit': 'Submit Repair Request',
    'repair.request.submitting': 'Submitting...',
    'repair.request.successTitle': 'Request Submitted',
    'repair.request.successMessage': 'Ticket Number: {ticketNumber}',
    'repair.request.successNote': 'Save this ticket number to track your repair status',
    'repair.request.errorTitle': 'Request Failed',
    'repair.request.errorMessage': 'An error occurred, please try again',
    
    'repair.lookup.title': 'Track Repair',
    'repair.lookup.description': 'Check your repair request status',
    'repair.lookup.ticketNumber': 'Ticket Number',
    'repair.lookup.ticketNumberPlaceholder': 'REP-00001',
    'repair.lookup.search': 'Search',
    'repair.lookup.searching': 'Searching...',
    'repair.lookup.notFound': 'Ticket not found',
    'repair.lookup.errorMessage': 'An error occurred while searching',
    
    'repair.ticket.details': 'Ticket Details',
    'repair.ticket.ticketNumber': 'Ticket Number',
    'repair.ticket.status': 'Status',
    'repair.ticket.priority': 'Priority',
    'repair.ticket.createdAt': 'Created At',
    'repair.ticket.updatedAt': 'Last Updated',
    'repair.ticket.estimatedCompletion': 'Estimated Completion',
    'repair.ticket.costEstimate': 'Estimated Cost',
    'repair.ticket.finalCost': 'Final Cost',
    'repair.ticket.technicianNotes': 'Technician Notes',
    'repair.ticket.customerName': 'Customer Name',
    'repair.ticket.customerPhone': 'Customer Phone',
    'repair.ticket.customerEmail': 'Customer Email',
    'repair.ticket.deviceType': 'Device Type',
    'repair.ticket.deviceBrand': 'Brand',
    'repair.ticket.deviceModel': 'Model',
    'repair.ticket.issueDescription': 'Issue Description',
    
    'repair.status.pending': 'Pending',
    'repair.status.in-progress': 'In Progress',
    'repair.status.waiting-parts': 'Waiting for Parts',
    'repair.status.completed': 'Completed',
    'repair.status.delivered': 'Delivered',
    
    'repair.priority.low': 'Low',
    'repair.priority.normal': 'Normal',
    'repair.priority.high': 'High',
    'repair.priority.urgent': 'Urgent',
    
    'repair.deviceType.laptop': 'Laptop',
    'repair.deviceType.desktop': 'Desktop',
    'repair.deviceType.monitor': 'Monitor',
    'repair.deviceType.printer': 'Printer',
    'repair.deviceType.other': 'Other',
    
    'repair.technician.login.title': 'Technician Login',
    'repair.technician.login.description': 'Enter your password to access the technician dashboard',
    'repair.technician.login.password': 'Password',
    'repair.technician.login.passwordPlaceholder': 'Enter password',
    'repair.technician.login.submit': 'Login',
    'repair.technician.login.successTitle': 'Logged In',
    'repair.technician.login.successDescription': 'Welcome back',
    'repair.technician.login.errorTitle': 'Error',
    'repair.technician.login.errorDescription': 'Incorrect password',
    'repair.technician.dashboard.title': 'Technician Dashboard',
    'repair.technician.dashboard.allTickets': 'All Tickets',
    'repair.technician.dashboard.newTicket': 'New Ticket',
    'repair.technician.dashboard.filterStatus': 'Filter by Status',
    'repair.technician.dashboard.filterPriority': 'Filter by Priority',
    'repair.technician.dashboard.searchPhone': 'Search by phone number...',
    'repair.technician.dashboard.noTickets': 'No tickets found',
    
    'repair.edit.title': 'Update Ticket',
    'repair.edit.updateStatus': 'Update Status',
    'repair.edit.updatePriority': 'Update Priority',
    'repair.edit.addNotes': 'Add Notes',
    'repair.edit.setEstimatedCompletion': 'Set Estimated Completion',
    'repair.edit.setCostEstimate': 'Set Estimated Cost',
    'repair.edit.setFinalCost': 'Set Final Cost',
    'repair.edit.save': 'Save Changes',
    'repair.edit.saving': 'Saving...',
    'repair.edit.successTitle': 'Updated',
    'repair.edit.successMessage': 'Ticket updated successfully',
    'repair.edit.errorMessage': 'Failed to update ticket',
    
    // Common
    'common.currency': 'IQD',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.ok': 'OK',
    'common.back': 'Back',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'ar') ? saved : 'ar';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, vars?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    if (vars) {
      Object.entries(vars).forEach(([varKey, value]) => {
        text = text.replace(`{${varKey}}`, value);
      });
    }
    return text;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
